### ISSUE TITLE
ClipboardItemData interface type missing array and function properties

### ISSUE THREAD

**Issue by wffurr** [microsoft/TypeScript-DOM-lib-generator#1000]
I tried generating the typings for the async Clipboard API in https://github.com/wffurr/TSJS-lib-generator/commit/9c8bc4b3c8003d48304a5fd439b981d221f33a8d and the generated `ClipboardItemData` type is missing the `types` and `getType` properties from the IDL:  https://w3c.github.io/clipboard-apis/#clipboard-interface

```
interface ClipboardItem {
  constructor(record<DOMString, ClipboardItemData> items,
    optional ClipboardItemOptions options = {});
  static ClipboardItem createDelayed(
      record<DOMString, ClipboardItemDelayedCallback> items,
      optional ClipboardItemOptions options = {});

  readonly attribute PresentationStyle presentationStyle;
  readonly attribute long long lastModified;
  readonly attribute boolean delayed;

  readonly attribute FrozenArray<DOMString> types;
  Promise<Blob> getType(DOMString type);
};
```

turns into this generated type: https://github.com/wffurr/TSJS-lib-generator/commit/9c8bc4b3c8003d48304a5fd439b981d221f33a8d#diff-d57c51d024219b9f37e6b42df127db25f700acbaade23ce1edcecda2853b995cR3587

```
interface ClipboardItem {
    readonly delayed: boolean;
    readonly lastModified: number;
    readonly presentationStyle: PresentationStyle;
}

declare var ClipboardItem: {
    prototype: ClipboardItem;
    new(items: Record<string, ClipboardItemData>, options?: ClipboardItemOptions): ClipboardItem;
    createDelayed(items: Record<string, ClipboardItemDelayedCallback>, options?: ClipboardItemOptions): ClipboardItem;
};
```

The interface should have `readonly types: string[]` and `getType(type: string): Promise<Blob>`.

**Comment by saschanaz** [comment]
#1034 added those two.

@github-actions close
