### ISSUE TITLE
window.location is read-only

### ISSUE THREAD

**Issue by Paril** [microsoft/TypeScript-DOM-lib-generator#1007]
https://html.spec.whatwg.org/multipage/history.html#the-location-interface

The spec allows window.location to be re-assigned to a string (or another Location object perhaps?) to navigate.

**Comment by Paril** [comment]
Update: in new version, `Location` is now not read-only, but is still not assignable to String.

**Comment by saschanaz** [comment]
Fixed by #996

**Comment by saschanaz** [comment]
@github-actions close
