### ISSUE TITLE
Add interfaces from CSS Animations Level 2 and CSS Transitions Level 2

### ISSUE THREAD

**Issue by birtles** [microsoft/TypeScript-DOM-lib-generator#1012]
These specs define the [`CSSAnimation`](https://drafts.csswg.org/css-animations-2/#cssanimation) and [`CSSTransition`](https://drafts.csswg.org/css-transitions-2/#csstransition) interfaces respectively which are implemented in all three major browser engines.

I believe we simply need to add the following URLs to [`idlSources.json`](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/master/inputfiles/idlSources.json):

* https://drafts.csswg.org/css-animations-2/
* https://drafts.csswg.org/css-transitions-2/

**Comment by birtles** [comment]
We shouldn't add `animationComposition` and `animationTimeline` from CSS Animations Level 2, however. No-one implements that.

**Comment by saschanaz** [comment]
Added by #1034

@github-actions close
