### ISSUE TITLE
type RequestInfo should include URL

### ISSUE THREAD

**Issue by aslilac** [microsoft/TypeScript-DOM-lib-generator#1016]
Currently `RequestInfo` is `Request | string`, but should (minimally) be `Request | URL | string`.

`fetch(new URL('/some_api', 'https://example.com'))` is valid, and works as you'd expect.

Technically it should be `Request | { toString(): string } | string` according to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch), but I'm not sure if there are intricacies around that.

**Comment by Paril** [comment]
I think the intricacy for the latter is that it's not very type-safe and more error-prone. They use the same thing for dataset/css style values, as well as other writeables, even if the spec allows and/or encourages it (for instance writing to `window.location` can be done with a string, and is most commonly done as such, but currently it's only writeable with a URL)

**Comment by partheseas** [comment]
Yeah, it feels like `{ toString(): string }` falls into almost all of the same pits as `{}` in that almost anything could be cast to it.

**Comment by orta** [comment]
Agree, I think we probably don't want this

**Comment by orta** [comment]
Related: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1003

**Comment by dnalborczyk** [comment]
> Agree, I think we probably don't want this

I would think _we do want_ this.

https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters

> A string or any other object with a stringifier — including a URL object — that provides the URL of the resource you want to fetch.

**Comment by dnalborczyk** [comment]
speaking of which, this is pretty much the same problem, but has been added:

https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/331
https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/332

**Comment by dnalborczyk** [comment]
and this as well: https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/600

`fetch` falls pretty much into the same category.
