### ISSUE TITLE
DOM Load and Save is missing

### ISSUE THREAD

**Issue by Mouvedia** [microsoft/TypeScript-DOM-lib-generator#1020]
https://www.w3.org/TR/DOM-Level-3-LS/load-save.html

`LSProgressEvent` and [`XMLDocument.load()`](https://developer.mozilla.org/en-US/docs/Web/API/XMLDocument/load) were supported by Firefox.
Most of the rest was supported by Opera.

- [x] Does the new objects or fields show up in mdn/browser-compat-data? (partially)
- [x] Is the IDL source from WHATWG or W3C? (W3C recommendation)
- [x] Are the additions available in at least two browsers? (yes)
- [x] Could any types added at the global scope have naming conflicts? (no)
- [ ] Are the new features going to be used by a lot of people?

<sup>
@orta told me to migrate DefinitelyTyped/DefinitelyTyped#28470 here
</sup>

**Comment by saschanaz** [comment]
>Are the additions available in at least two browsers?

It's not "are" here, it's "were", right? I'm doubt those APIs deserve to be here then...

**Comment by saschanaz** [comment]
@github-actions close
