### ISSUE TITLE
Add disposition field to SecurityPolicyViolationEvent interface

### ISSUE THREAD

**Issue by bsafwen** [microsoft/TypeScript-DOM-lib-generator#1030]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2015` and my *lib* is `["esnext", "dom"]`.

## Missing / Incorrect Definition

the interface SecurityPolicyViolationEvent is missing the `disposition` field.

## Sample Code
```typescript
private checkSecPolicyViolation(event: SecurityPolicyViolationEvent) {
    if (event.disposition === 'report') return "not important";
    else if (event.disposition === 'enforce') return "something needs to be done";
}
```

## Documentation Link

According to https://www.w3.org/TR/CSP3/#violation-events, the interface SecurityPolicyViolationEvent has a field called disposition. This field is present in Chrome, Firefox, Safari.

**Comment by andrewbranch** [comment]
Transferred to TypeScript-DOM-lib-generator. Feel free to check the README and open a PR. Thanks!

**Comment by tosmolka** [comment]
Was this issue fixed by https://github.com/saschanaz/types-web/commit/86b265a8549689b8f6c03aea79df816a8b1ede35 or we still need https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1037 ?

**Comment by saschanaz** [comment]
Yeah, #1034 did it.

@github-actions close
