### ISSUE TITLE
Should we keep track of the last date an IDL was processed as a baseline?

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-DOM-lib-generator#1033]
For a PR like https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1031 - I'm not certain if this was done via the IDL generator, or hand added in the JSON (as that probably seems like the easiest way as a first time contributor) 

If we had a JSON file which had the dates the last time a IDL was processed (which gets updated when someone runs the scripts) then we can know in a PR that it isn't a temporary change

**Comment by saschanaz** [comment]
The IDL generator never touches `browser.webidl.preprocessed.json` and it should not be modified by anything. That's why https://github.com/microsoft/TypeScript-DOM-lib-generator/commits/master/inputfiles/browser.webidl.preprocessed.json is very short (and it means #662 was wrong).

**Comment by saschanaz** [comment]
Closing this as there is no `browser.webidl.preprocessed.json` anymore

@github-actions close
