### ISSUE TITLE
The `Headers` type should be iterable

### ISSUE THREAD

**Issue by glen-84** [microsoft/TypeScript-DOM-lib-generator#1069]
Works in Chrome, Edge, and Firefox:

```ts
const headers = new Headers({a: 1, b: 2});

console.log(Object.fromEntries(headers));
```

In TS:

> No overload matches this call.
  Overload 1 of 2, '(entries: Iterable<readonly [PropertyKey, any]>): { [k: string]: any; }', gave the following error.
    Argument of type 'Headers' is not assignable to parameter of type 'Iterable<readonly [PropertyKey, any]>'.
      Property '[Symbol.iterator]' is missing in type 'Headers' but required in type 'Iterable<readonly [PropertyKey, any]>'.
  Overload 2 of 2, '(entries: Iterable<readonly any[]>): any', gave the following error.
    Argument of type 'Headers' is not assignable to parameter of type 'Iterable<readonly any[]>'.
      Property '[Symbol.iterator]' is missing in type 'Headers' but required in type 'Iterable<readonly any[]>'.

https://developer.mozilla.org/en-US/docs/Web/API/Headers#browser_compatibility
https://caniuse.com/mdn-api_headers_--iterator

**Edit:** While we're on the subject, is there any reason not to add `entries`, `keys`, and `values`?

**Comment by saschanaz** [comment]
[It is already iterable](https://www.typescriptlang.org/play?target=6&ssl=3&ssc=42&pln=1&pc=1#code/MYewdgzgLgBAFgUwIYBMECcIwLwzAgdxgAlk1MAKAbyQC4YAiARgYBoYAjehgJgYF8AlAG4AsACgJoSCAA2CAHSyQAcwoB5DgCsEwKAoBm6EAFsAomCjoAlgggVEqDBEEigA). What does your current configuration look like?

**Comment by glen-84** [comment]
Apologies, I should have tried with the max settings.

I'm using `"target": "ES2017"` and `"lib": ["ES2019.Object"]`. Do you know where this was added? I can't really change the target, so if that is required I'll just use a workaround.

Thanks.

**Comment by saschanaz** [comment]
Hmm, so you are using `@types/web`, right?

@orta, how can `index.iterable.d.ts` be used when using the package?

**Comment by glen-84** [comment]
> Hmm, so you are using `@types/web`, right?

No, I actually have no idea what that is. 😟 Seems new.

I'm using TS 4.3.5 and tslib 2.3.0.

Looks like I need to add `DOM.Iterable` to `lib`. I'm not sure how to check compatibility, or why it's necessary to manually include this, etc.

Anyway, thanks for your help. 🙂

**Comment by saschanaz** [comment]
`dom` and `dom.iterable` are included by default but not when you manually set the `lib` field, that's why 😁

**Comment by glen-84** [comment]
Ahhh, so when I added `ES2019.Object` for `Object.fromEntries`, I lost `dom` and `dom.iterable`.

Thanks a lot!
