### ISSUE TITLE
`caretRangeFromPoint` return type should be `Range | null`

### ISSUE THREAD

**Issue by melink14** [microsoft/TypeScript-DOM-lib-generator#1072]
# `caretRangeFromPoint` Update Request

## Configuration Check

My compilation *target* is `ES2020` and my *lib* is `caretRangeFromPoint`.

## Missing / Incorrect Definition

`caretRangeFromPoint` is currently defined as:
```
caretRangeFromPoint(x: number, y: number): Range;
```
but should be
```
caretRangeFromPoint(x: number, y: number): Range | null;
```

## Sample Code

```
// Calculate range and friends here after we've made our fake textarea/input divs.
range = document.caretRangeFromPoint(ev.clientX, ev.clientY);
const startNode = range.startContainer;
```
This code should have a type error but currently doesn't since library doens't show return type as nullable. This happens quite often in the wild.

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint also shows null as possible return type.

**Comment by melink14** [comment]
Ah, I filed based on reading the commits that added it but it seems it was deleted from this repo in:
https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/3575d1b7c760e2bbf44a5b62e23e146055a00bbc#diff-72e8dfbf8f82281b296a7355a166f0d69adbcc4957ba52f66d7c32be0b62cc41

But it still is in Typescript's generated DOM types so does maybe somewhere here no how lesser supported APIs end up there?

**Comment by saschanaz** [comment]
Hmm, it's one of rare thing that exists in browsers but not in the spec. I filed https://github.com/w3c/csswg-drafts/issues/6459 and will add this one manually.
