### ISSUE TITLE
Fix TS_GITHUB_BOT_AUTH access permission

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1079]
It needs public_repo *read* access. @orta

**Comment by saschanaz** [comment]
@orta Adding read access should be no-brainer, what's blocking it? 😬

**Comment by orta** [comment]
I think the workflow is probably misconfigured, the token does have read access but it doesn't have write access to this repo:

```
Pushing pull request branch to 'origin/update-core-deps'
  /usr/bin/git push --force-with-lease origin HEAD:refs/heads/update-core-deps
  remote: Permission to microsoft/TypeScript-DOM-lib-generator.git denied to typescript-bot.
  fatal: unable to access 'https://github.com/microsoft/TypeScript-DOM-lib-generator/': The requested URL returned error: 403
```
[logs](https://github.com/microsoft/TypeScript-DOM-lib-generator/runs/3430443920?check_suite_focus=true#step:10:69)

Maybe there's a setting for declaring what repo to send a fork from?

**Comment by saschanaz** [comment]
Hmm, it seems `public_repo` automatically allowed write access for me since the token was from the repo owner account. Not if it's from the bot account, for sure. Can the bot have a fork?
