### ISSUE TITLE
ChildNode/ParentNode no longer extending Node

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-DOM-lib-generator#1087]
According to https://github.com/microsoft/TypeScript/issues/45266, there are some breaks around [`ChildNode` no longer being a subtype of `Node`](https://github.com/microsoft/TypeScript/commit/9ebe11c2d375bfb1c8fad10d705ffae09583c522#diff-dc0eab937d15e62545da3ed7b4f40ad6b24f15dd88fbc6ceda2bfb4ed8356eb0L3511). This was also mentioned in Google's 4.4 beta adoption thread (#1067).

<details>
<summary>
Some breaks here
</summary>

> # [ant-design/ant-design](https://github.com/ant-design/ant-design)
> ### [tsconfig.json](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/tsconfig.json)
>  - `error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.`
>    - [components/_util/scrollTo.ts#L26](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/components/_util/scrollTo.ts#L26)
>  - `error TS2339: Property 'nodeType' does not exist on type 'ChildNode'.`
>    - [components/typography/util.tsx#L143](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/components/typography/util.tsx#L143)
>    - [components/typography/util.tsx#L207](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/components/typography/util.tsx#L207)
>  - `error TS2345: Argument of type 'ChildNode' is not assignable to parameter of type 'Node'.`
>    - [components/typography/util.tsx#L160](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/components/typography/util.tsx#L160)
>    - [components/typography/util.tsx#L165](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/components/typography/util.tsx#L165)
>    - [components/typography/util.tsx#L220](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/components/typography/util.tsx#L220)
>  - `error TS2339: Property 'textContent' does not exist on type 'ChildNode'.`
>    - [components/typography/util.tsx#L227](https://github.com/ant-design/ant-design/blob/015b70664317917969ef5580cbc2dfb533dc0c02/components/typography/util.tsx#L227)

> # [sindresorhus/refined-github](https://github.com/sindresorhus/refined-github)
> ### [tsconfig.json](https://github.com/sindresorhus/refined-github/blob/4af1669e2dba94a1d170dfe563b88416582be716/tsconfig.json)
>  - `error TS2345: Argument of type 'Element | ChildNode' is not assignable to parameter of type 'string | Node'.`
>    - [source/helpers/dom-utils.ts#L48](https://github.com/sindresorhus/refined-github/blob/4af1669e2dba94a1d170dfe563b88416582be716/source/helpers/dom-utils.ts#L48)

</details>

In #1067, @saschanaz explained

> It's a mixin interface implemented by some Node interfaces. The correct way to receive Nodes that can be children is `ChildNode & Node`, just like `ParentNode & Node` for Nodes that can be parents.

I may be missing some context of why that's important to have - was there discussion around that? But regardless, I don't know if we can retroactively make that call. If that's a thing users need, does it make sense to create a `ChildNodeBase` and a `ParentNodeBase`?

**Comment by saschanaz** [comment]
Adding `type ChildNodeBase = ChildNode & Node` etc. makes sense to me.

**Comment by DanielRosenwasser** [comment]
> Adding `type ChildNodeBase = ChildNode & Node` etc. makes sense to me.

Sorry, I meant rename `ChildNode` to `ChildNodeBase`, re-declare `ChildNode` as

```ts
interface ChildNode extends ChildNodeBase, Node {}
```

and swap all the uses of `ChildNodeBase & Node` to `ChildNode`.

> Restoring the previous `ChildNode` is also an option.

To be honest, I'm leaning the strongest on this one. We can always make that other change sooner, but I am apprehensive about shipping this break.

**Comment by saschanaz** [comment]
👍 from me for that idea.

**Comment by DanielRosenwasser** [comment]
Is there an easy place to fix this? I can see the `overrideTypes.json` for the references, but it's unclear to me where to make the change for the declarations of `ChildNode` and `ParentNode`.

**Comment by saschanaz** [comment]
You can insert the following somewhere below "mixins":

```js
"ChildNode": {
  "name": "ChildNodeBase"
}
```

And then somewhere below "interfaces":

```js
"ChildNode": {
  "name": "ChildNode",
  "implements": ["ChildNodeBase", "Node"]
}
```

**Comment by DanielRosenwasser** [comment]
Sorry, I meant to revert the change and go back to the original definitions of `ChildNode` - but that was still helpful. I'll have a PR soon.

**Comment by saschanaz** [comment]
That should implement your idea https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1087#issuecomment-891333791

**Comment by DanielRosenwasser** [comment]
I wasn't sure whether it was worth it to define the new `*Base` types, so I've left them out for now. I figured that if it's really broadly needed, we could introduce them in 4.5.
