### ISSUE TITLE
DOMException should extend Error

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/TypeScript-DOM-lib-generator#1099]
Fun fact that code below evaluates to `true`.

```js
DOMException.prototype instanceof Error
&& new DOMException() instanceof Error
```

I'm not familiar with the technical details, but noticed that Web IDL suggest:

> Additionally, if an implementation gives native Error objects special powers or nonstandard properties (such as a `stack` property), it should also expose those on [DOMException](https://heycam.github.io/webidl/#idl-DOMException) instances.
>
> — [DOMException custom bindings](https://heycam.github.io/webidl/#es-DOMException-specialness)

which sounds just like "interface DOMException extends Error".

And this matters in cases like https://github.com/typescript-eslint/typescript-eslint/issues/3712. 👀

Thank you!

**Comment by saschanaz** [comment]
👍. FWIW the relevant phrase is actually the right above one:

>In the ECMAScript binding, the interface prototype object for DOMException has its [[Prototype]] internal slot set to the intrinsic object %Error.prototype%, as defined in the create an interface prototype object abstract operation.
