### ISSUE TITLE
Object.entries(typedObject).forEach forgets the types

### ISSUE THREAD

**Issue by NorfeldtAbtion** [microsoft/TypeScript-DOM-lib-generator#1101]
https://stackoverflow.com/questions/68742597/typescript-forgets-the-types-when-using-object-entriestypedobject-foreach

EXAMPLE:

```js
type Tkey = 'foo' | 'bar' | 'defaultKey'

const typedObject: Record<Tkey, string[]> = {
 'foo': ['1', '2'],
 'bar': ['3'],
 'defaultKey': []
}


let returnKey: Tkey = 'defaultKey'

Object.entries(typedObject).forEach(([key, values]) => {
  if (values.includes('3') returnKey = key
})
```

vscode keeps telling me that `key` in `([key, values])` is of type `string` and not of type `Tkey`.

[![enter image description here][1]][1]

The current answer is: 

> TypeScript's native definition files contain this for Object.entries:
> 
> ```ts
> entries<T>(o: { [s: string]: T } | ArrayLike<T>): [string, T][];
> 
> entries(o: {}): [string, any][];
> ```
> 
> Your only chance to get the behavior you want is to override this definition with something like this:
> 
> ```
> interface YourOwnObject {
>   entries<T>(o: { [K in keyof T]: T[K] }): [keyof T, T[keyof T]][];
> }
> 
> (<YourOwnObject>Object).entries(typedObject).forEach(([key, values]) => {
>   // ...
> })
> ```

  [1]: https://i.stack.imgur.com/VA1Bh.png

**Comment by saschanaz** [comment]
This repository is only for web APIs, and the JS things should go TypeScript repo instead.
