### ISSUE TITLE
Let OSS-Docs-Tools/code-owner-self-merge use Personal Access Token

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1103]
Merging by `secrets.GITHUB_TOKEN` does not fire workflows, see https://github.com/peter-evans/create-pull-request/blob/master/docs/concepts-guidelines.md#triggering-further-workflow-runs

I think it should also use TS_GITHUB_BOT_AUTH, but I guess it would need a write access in that case?

**Comment by orta** [comment]
This makes sense, I think we can solve this with a nightly scheduled run of the CI! The deploy scripts would NOOP today if there are no changes anyway.

It's what I do for https://github.com/tsconfig/bases

**Comment by saschanaz** [comment]
Doing nightly runs sounds good to me

**Comment by orta** [comment]
That worked this morning
