### ISSUE TITLE
interface AudioScheduledSourceNode.start() has wrong spec

### ISSUE THREAD

**Issue by yoshikiohshima** [microsoft/TypeScript-DOM-lib-generator#1107]
The MDN Web Docs states that AudioScheduledSourceNode.start() can take up to three arguments (c.f. https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/start)

 However, the corresponding line i dom.generated.d.ts:

https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/f9b2f22f230d32caf1758146631ea01cae1a2815/baselines/dom.generated.d.ts#L2198

specifies only one optional argument.

**Comment by saschanaz** [comment]
It seems MDN wrongly copied AudioBufferSourceNode which does accept three arguments. [AudioScheduledSourceNode does not](https://webaudio.github.io/web-audio-api/#AudioScheduledSourceNode).

**Comment by HolgerJeromin** [comment]
I think we can close this item here... Thanks for the hint!

**Comment by yoshikiohshima** [comment]
Very interesting! As pointed out, the spec certainly states that start() only takes one argument, but back when I was writing this app, which I am now porting to TypeScript, in JS, giving other two arguments to start() did change its behavior. I took out other arguments and it does not break. I am a bit curious what happened since then but in any case thank you for looking into it!
