### ISSUE TITLE
`npm i` installs older dependencies

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1110]
Because package.json is not being updated. This can be a hurdle for contributors.

**Comment by orta** [comment]
Dependabot doesn't seem to be making PRs, https://github.com/microsoft/TypeScript-DOM-lib-generator/pulls?q=is%3Apr+author%3Aapp%2Fdependabot

**Comment by ExE-Boss** [comment]
Refs <https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1173#issuecomment-932809285>:
> Unfortunately https://github.com/OSS-Docs-Tools/code-owner-self-merge does not support partial ownership of package.json 😬 <https://github.com/OSS-Docs-Tools/code-owner-self-merge/issues/29>
