### ISSUE TITLE
Bump for adding ElementInternals

### ISSUE THREAD

**Issue by Vac1911** [microsoft/TypeScript-DOM-lib-generator#1114]
Opening an issue to please add the ElementInternals interface and related API: HTMLElement.attachInternals().
The functionality is supported by Chrome, Edge, and Opera _[source](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals#browser_compatibility)_. This feature is also experimentally available in Firefox.

I believe pull request #818 would solve the problem, however it has seem to have gone stale. Recently as customElements are becoming more popular I thought I would ask the maintainers to reconsider. Thank you!

**Comment by orta** [comment]
Thanks for the pokiest. I re-ran the API examples linked to in that PR for Safari and Firefox just now and they still aren't available a year later - so I'm afraid PR is not stale, it's that there's still only one browser engine which supports it.

**Comment by radium-v** [comment]
Hi, there are more properties and methods on `ElementInternals` which should now be supported in major browsers:

* [`checkValidity()`](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/checkValidity)
* [`reportValidity()`](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/reportValidity)
* [`validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/validationMessage)
* [`validity`](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/validity)

(`states` are currently supported everywhere but Firefox, where it's behind the `dom.element.customstateset.enabled` flag).

**Comment by HolgerJeromin** [comment]
@radium-v They are already part of the output:
https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/6621974de7d3d03ade59760ea4b1cdb12698f492/baselines/dom.generated.d.ts#L7996
