### ISSUE TITLE
backdropFilter missing from CSSStyleDeclaration

### ISSUE THREAD

**Issue by bmckilligan** [microsoft/TypeScript-DOM-lib-generator#1118]
# Bug Report

interface CSSStyleDeclaration  needs backdropFilter added
https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts

### 🔎 Search Terms

CSSStyleDeclaration
backdropFilter

### 🕗 Version & Regression Information

4.4

**Comment by saschanaz** [comment]
Fixed by #1394

@github-actions close
