### ISSUE TITLE
ARIAMixin properties should be nullable?

### ISSUE THREAD

**Issue by h-joo** [microsoft/TypeScript-DOM-lib-generator#1119]
In the [ARIAMixin](https://github.com/microsoft/TypeScript/blob/v4.4-rc/lib/lib.dom.d.ts#L1859) definition of TS 4.4-rc, the aria* properties are non-nullable, but according to the [spec draft](https://wicg.github.io/aom/spec/aria-reflection.html#dfn-ariaattributes) for AOM aria reflection with the AriaAttributes mixin, it seems to be nullable. Should these types need to be reconsidered to be nullable?

**Comment by jnurthen** [comment]
Note https://github.com/w3c/aria/pull/1611 makes them nullable again.

**Comment by saschanaz** [comment]
Thanks, in that case it will be updated by webref within a few days.

**Comment by saschanaz** [comment]
Fixed by #1200

@github-actions close
