### ISSUE TITLE
Better typing for exactOptionalPropertyTypes needed

### ISSUE THREAD

**Issue by HolgerJeromin** [microsoft/TypeScript-DOM-lib-generator#1126]
I did not find a "planning" issue in this or TS repository.
All types from this repository should be safe to use with the new Typescript option.

Got this error but I am quite sure this is a problem with many definitions:

```ts
            let IntlOptions: Intl.DateTimeFormatOptions = {
                timeZone: undefined
            };
```
ref #1092

**Comment by saschanaz** [comment]
Intl APIs from ECMAScript spec and bugs about it should go TypeScript repo instead.
