### ISSUE TITLE
`PermissionName` missing values

### ISSUE THREAD

**Issue by dhaigh** [microsoft/TypeScript-DOM-lib-generator#1129]
there are many missing permission names in TS 4.4, including the frequently-used `camera` and `microphone`

https://www.typescriptlang.org/play?#code/HYQwbglg5iAuD2AnAdABwKaILYQM64nmF2QEcBXTATwAoBvULdALgAIByAYxCcRHYC+ASgDcAKFCQYCFBmx4CREhWr1GLDjk6J4qABZF0g0WKA

according to [the latest version of the spec](https://w3c.github.io/permissions/#dom-permissionname) the values are:
```
  "accelerometer",
  "ambient-light-sensor",
  "background-fetch",
  "background-sync",
  "bluetooth",
  "camera",
  "display-capture",
  "geolocation",
  "gyroscope",
  "magnetometer",
  "microphone",
  "midi",
  "nfc",
  "notifications",
  "persistent-storage",
  "push",
  "screen-wake-lock",
  "speaker-selection",
  "xr-spatial-tracking",
```

TS 4.4.2 gives `PermissionName` as:
```ts
type PermissionName = "gamepad" | "geolocation" | "notifications" | "persistent-storage" | "push" | "screen-wake-lock";
```

**Comment by saschanaz** [comment]
Those are at risk with lack of broad implementation, also per the latest spec 👀

https://w3c.github.io/permissions/#dom-permissionname-camera

>This powerful feature only has a single implementation, and therefore, as per the W3C Process, it is at risk.
