### ISSUE TITLE
Should MediaRecorderEventMap use MediaRecorderErrorEvent?

### ISSUE THREAD

**Issue by frigus02** [microsoft/TypeScript-DOM-lib-generator#1138]
The new MediaRecorderEventMap currently maps the `error` event to a basic `Event` type:

https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/fa11d129b123258298af34059d8c4726d512fb80/baselines/dom.generated.d.ts#L9016

If I read the spec correctly ([error summary section](https://w3c.github.io/mediacapture-record/#event-summary)), the error event should use `MediaRecorderErrorEvent`.

Is there a reason for this or is this a bug?

**Comment by saschanaz** [comment]
Seems like a bug. PR welcome 👍
