### ISSUE TITLE
noiseSuppression property missing in MediaTrackConstraintSet

### ISSUE THREAD

**Issue by zaphod534** [microsoft/TypeScript-DOM-lib-generator#1148]
# Bug Report

### 🔎 Search Terms

MediaTrackConstraints

### 🕗 Version & Regression Information

- This changed between versions 4.3.5 and 4.4.4

### 🙁 Actual behavior

In `MediaTrackConstraintSet` the property `noiseSuppression` is not present
### 🙂 Expected behavior

In `MediaTrackConstraintSet` the property `noiseSuppression` should be present since it is present in [webrtc official spec](https://w3c.github.io/mediacapture-main/#media-track-constraints)

**Comment by orta** [comment]
This is only available in Chromium, so that's waiting on other browsers to implement and use it.

https://caniuse.com/?search=noiseSuppression

**Comment by saschanaz** [comment]
I think you misread, it says Firefox 55+ supports it.

**Comment by paulgalow** [comment]
I'd like to add the `autoGainControl` property which is supported in Chromium and Firefox according to [Can I use](https://caniuse.com/?search=autoGainControl) and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/autoGainControl#browser_compatibility).

**Comment by saschanaz** [comment]
PR welcome for both of them 👍

**Comment by paulgalow** [comment]
Thanks. I'm on it …

**Comment by saschanaz** [comment]
Fixed by #1152 

@github-actions close
