### ISSUE TITLE
`Node.parentElement` should be `Element | null`, not `HTMLElement | null`

### ISSUE THREAD

**Issue by trusktr** [microsoft/TypeScript-DOM-lib-generator#1151]
Hello! I'm new to this. How exactly would I change that?

For example, a `<g>` element somewhere inside an `<svg>` element will have a `.parentElement` that is an `SVGElement`, which is not an `HTMLElement`.

**Comment by saschanaz** [comment]
This is true and was done by #885, but then reverted by #970. Seems there were tons of breakages. @orta

I doubt we can do this if that was the case, but it should at least need some comment about it.

**Comment by trusktr** [comment]
I left some comments. Plus imagine when something useful like this comes out in the future:

https://github.com/WICG/webcomponents/issues/942

The only proper type for these DOM APIs is `Element`.

**Comment by HolgerJeromin** [comment]
@trusktr 
Technically you are right in moving to `Element`. But this would break many applications. Most do only deal with HTML and would need manual adjustments. 
Developers should be happy and not annoyed by forcing them to touch all DOM touching code with compiled for years.
SVG users are right now forced to type assert anyway.

ref https://github.com/microsoft/TypeScript/pull/42067#issuecomment-754860862

**Comment by orta** [comment]
Yeah, this has been well covered  and discussed. I don't think I've seen anything new in the comments to warrant keeping this issue around. If you'd like you, can fork this repo to ship your own dom.d.ts build with this in 4.5, but it's unlikely to come in by default given the trade-offs.
