### ISSUE TITLE
Inconsistency between input event and beforeinput event

### ISSUE THREAD

**Issue by sapphi-red** [microsoft/TypeScript-DOM-lib-generator#1174]
Now beforeinput event is `InputEvent` (because it is defined with addedTypes [here](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/5706098631f053f8000a2844f2819f574756ffeb/inputfiles/addedTypes.jsonc#L64-L65)).
On the other hand, input event is `Event` (this is from [HTML Standard](https://html.spec.whatwg.org/multipage/indices.html#event-input-input)).

[`beforeinput` event is defined in UIEvents](https://www.w3.org/TR/uievents/#event-type-beforeinput) and here it is defined that [`input` is also `InputEvent`](https://www.w3.org/TR/uievents/#event-type-input).

I think input event should be `InputEvent`.

**Comment by saschanaz** [comment]
This is because `input` does not always use `InputEvent`. Copy below to the address bar and see what happen on the console.

`data:text/html,<input type=range oninput="console.log(event.constructor.name)"><input type=text oninput="console.log(event.constructor.name)">`

On `input[type=range]` the event uses `Event` and on `input[type=text]` it uses `InputEvent`. To cover both it should be `Event` rather than `InputEvent`.

**Comment by sapphi-red** [comment]
I see.
Thank you!

**Comment by L1Q** [comment]
Is there a way to specify it can be both? I'd expect `GlobalEventHandlersEventMap` in `lib.dom.d.ts` to state 
``
    "input": Event | InputEvent;
``

**Comment by saschanaz** [comment]
That's no different than just Event, though...

**Comment by L1Q** [comment]
Union types TS open the way for type guards and optional chaining. The current way only calls for unsafe type casts.

**Comment by saschanaz** [comment]
Event is a strict superset of InputEvent and thus unioning them just gives Event, with no additional type gaurd.

**Comment by L1Q** [comment]
You *can* provide your own guard though.

**Comment by saschanaz** [comment]
How?

**Comment by L1Q** [comment]
Basically, this works perfectly fine, correctness-wise
```ts
const input = document.createElement('input')
input.setAttribute('type', 'text')
input.addEventListener('input', (ev: Event) => {
    if(ev instanceof InputEvent) {
        console.log('inputting text using input type:', ev.inputType)
        input.setAttribute('type', 'range')
    } else {
        console.log('manipulating slider')
        input.setAttribute('type', 'text')
    }
})
document.body.appendChild(input)
```

[>> playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmADgV1gXhgExMZBbAUzCgDpgAnAgQygIFEAbAw4gCgHIEUp2BKAWABQXVCQgEoAQShRycAEaoCHKAE9EBdgBoY7WgA8eA4UlFVMmOgDciUADJxoRAuQ4ieO1gSsAuGNdteGDQAPhgAbyEYaPgAMy8reEgoKjBgAhBYmABJUygA4iDIwRjSmFBIECYSBhAAczc8qAQ6mANYZAgWpO429QIfbRhvEncAFX7jMpj3MQlpWQUlFX6h9nJUus0pmIBfYYZxCKjp8vAIKoIa+o48VLgUBhpuiAY4TBc+E+nZ8SkZOSKWgrDRrdpfEp7IS7YzYXAsUjyECYVQkKiIDRgTAAYQAFnAGJhWO5jEA)

**Comment by saschanaz** [comment]
And that works without union type, right? 🤔

**Comment by L1Q** [comment]
> And that works without union type, right? thinking

yep

**Comment by saschanaz** [comment]
Sorry for not reading the latest version of the comment 😬

Anyway, please feel free to open new issues when you find one! 👍
