### ISSUE TITLE
Type CSS and HTML lengths with templates

### ISSUE THREAD

**Issue by mrbrianevans** [microsoft/TypeScript-DOM-lib-generator#1179]
I would like to make a suggestion, to make the types more specific for HTML and CSS lengths.

Presently, attributes such as `height` are typed as being `string`. They have to allow string rather than number because of the measurement that follows a number, such as `10px` or `1.2rem`.

I think this can be improved using Typescript templates, by doing something like this instead:
```typescript
type Length = number | `${number}${'px'|'ch'|'pt'|'cm'|'in'|'em'|''}`;

interface SomeElement {
    height?: Length
}
```

This would result in:
```tsx
<SomeElement height={'5px'} /> // allowed
<SomeElement height={'asdf'} /> // compile time error
```

If this is agreed upon, I will start implementing it.

**Comment by mrbrianevans** [comment]
[Typescript playground example](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnADJYB2A5jABZwAvHC4BXEACMsUOAB84AAwAkAb3FSZAXzVkwADzJyyufkb0xzuEOeBdzWG8bJbF9OnZgyCeNgGUSLABRABtHbhgABWIwdFU6OES4fixgHn4YAH4ALg5uPn46LQZcCC5UeACQYLDqrhhc7DwYADoAMQBhAB4qmvD66IhYgD5hOAAKVRS0jK0ASmFR+KS4ShgxKC44LrBhgAlU9Ia4KcPZroB6XaKSsoq4UvAxruGEpJ7A0P74aaOhVTIAFYDC44BdRhcLigQiEIAB3LAAEzeiQ+1S+dR+Zxg-zIaERBFB4LBUMeYGAYTgMFAbBkxCgdEuwyAA)

**Comment by orta** [comment]
It's a compelling idea, I'm not really sure how to test it doesn't end up being a massive ecosystem break though 👍🏻

**Comment by mrbrianevans** [comment]
I could do some testing on popular widget libraries to see if it breaks.

I can't think of any case where it would intentionally be set to a value that would cause a compile time error, so any errors probably reflect genuine problems.

Another idea, is to maybe add a compiler option to tsconfig, and disable it by default if it would break many projects, but at least projects can choose to opt-in?
