### ISSUE TITLE
Incorrect type declaration for CryptoKeyPair

### ISSUE THREAD

**Issue by m-day** [microsoft/TypeScript-DOM-lib-generator#1186]
See [microsoft/TypeScript/46036](https://github.com/microsoft/TypeScript/issues/46036)

also acknowledged here: [TypeScript-DOM-lib-generator/issues/1029](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029#issuecomment-898868533)

**Comment by saschanaz** [comment]
The PR is merged.

@github-actions close
