### ISSUE TITLE
Autogenerate `type Transferable`

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1197]
It's essentially the list of interfaces with `[Transferable]` extended attribute. It already lacks stream objects which are transferable, it should be autogenerated to prevent such omission rather than manually defined in overrideTypes.json.

**Comment by jespertheend** [comment]
Stream objects are not transferable on Safari: https://wpt.fyi/results/streams/transferable?label=experimental&label=master&aligned
I think that's why they're omitted.

**Comment by saschanaz** [comment]
Two supported browser engines fulfills the requirement, so no, it's purely a automation issue.
