### ISSUE TITLE
`DOMStringList` missing iterator method

### ISSUE THREAD

**Issue by advaith1** [microsoft/TypeScript-DOM-lib-generator#1208]
TypeScript blocks using `[...location.ancestorOrigins]` with the error
> Type 'DOMStringList' must have a '\[Symbol.iterator]()' method that returns an iterator. ts(2488)

However, it is present in Chrome:
![image](https://user-images.githubusercontent.com/11778454/143518176-f340d276-3b05-45f7-a13a-bc4c8b63b469.png)

**Comment by saschanaz** [comment]
It exists:

https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/2173711b06b303e39ba0c1c4a3c6921ba48f7616/baselines/dom.iterable.generated.d.ts#L37-L39

What does your tsconfig look like?

**Comment by advaith1** [comment]
here's the tsconfig: https://github.com/widgetbot-io/embed/blob/master/tsconfig.json

here are the DOMStringList definitions VSCode found:

![image](https://user-images.githubusercontent.com/11778454/144479560-a8f6f095-7bc1-49d2-ba51-77061aeb07d6.png)
![image](https://user-images.githubusercontent.com/11778454/144479593-69e17931-585b-47bb-b389-c4c67928db10.png)

It's using VSCode's TS version (4.5.2) but I get the same error if I switch to the workspace version (4.2.2)

**Comment by saschanaz** [comment]
Ah sure, you also need to include "dom.iterable" next to "dom".

**Comment by saschanaz** [comment]
@orta could this kind of thing be autosuggested? 🤔

**Comment by orta** [comment]
We've got a big chunk of checks in `getCannotFindNameDiagnosticForName` inside the compiler, (no point offering a link to the checker) but this can probably be added to that list. You have to manually set up your `lib` settings like this to trigger this case  as the iteration version would be added by default if you include es2015/es6+ in your target

**Comment by advaith1** [comment]
> Ah sure, you also need to include "dom.iterable" next to "dom".

Thanks, that worked! Is there a reason it isn't included in dom?

**Comment by saschanaz** [comment]
> We've got a big chunk of checks in `getCannotFindNameDiagnosticForName` inside the compiler, (no point offering a link to the checker) but this can probably be added to that list.

There is no applicable identifier here (it's `...`), so I guess there should be some tweak.

> Thanks, that worked! Is there a reason it isn't included in dom?

`target: es5` does not support iterators, so including it by default would be confusing. But not including it is also confusing in 2021. 🤔

**Comment by saschanaz** [comment]
This is solved, right?

@github-actions close
