### ISSUE TITLE
NPM deployment has been failing since Nov 18

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#1210]
@orta could you take a look?

**Comment by orta** [comment]
Really confused what's up with this now. The token is correct, and it logs in:

https://github.com/microsoft/TypeScript-DOM-lib-generator/runs/4449076104?check_suite_focus=true#step:9:10 shows we're logged in as `types`, then it somehow isn't logged in when it deploys the package: https://github.com/microsoft/TypeScript-DOM-lib-generator/runs/4449076104?check_suite_focus=true#step:9:58

**Comment by saschanaz** [comment]
Theres' https://github.com/npm/cli/pull/2602 but this shouldn't affect us as CI uses npm 8.1.0. Still, how about doing `npm i -g npm@latest` and try again?

**Comment by orta** [comment]
That was it: https://github.com/microsoft/TypeScript-DOM-lib-generator/releases
