### ISSUE TITLE
Missing "charset" on HTMLMetaElement

### ISSUE THREAD

**Issue by chronoDave** [microsoft/TypeScript-DOM-lib-generator#1223]
Hey there,

I'm currently working on implementing JSX syntax into my project and noticed that `HTMLMetaElement` is missing the `charset` attribute. I've read the Contribution Guidelines and think this would fall under the "When the type is missing", as it is defined on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset).

If I read the docs correctly, it seems that `charset` is not included in `inputfiles/removedTypes.jsonc`. Is it possible for this type to be added, and if so, how can I contribute?

**Comment by saschanaz** [comment]
There is no such thing like `HTMLMetaElement.prototype.charset`. I guess you want to install `@types/react` and do `<meta charSet>`. (Yes, `charSet`.)

**Comment by chronoDave** [comment]
Thank you, I'm not using React myself so I won't need the types for it. Where can I find more information about `HTMLMetaElement.prototype`?

It seems odd to me that `charset` does exist on [`HTMLAnchorElement`](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.generated.d.ts#L5787) and [`HTMLLinkElement`](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.generated.d.ts#L6915) but not on [`HTMLMetaElement`](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.generated.d.ts#L7129) (albeit deprecated) even though it's listed as a non-deprecated property on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-charset)

**Comment by saschanaz** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMetaElement and https://html.spec.whatwg.org/multipage/semantics.html#htmlmetaelement should help you.

**Comment by chronoDave** [comment]
Thank you for those docs, they are indeed quite helpful! Looking at the html spec, it shows `charset` being part of the content attributes but it is not defined in the DOM interface, how does that work?

**Comment by saschanaz** [comment]
In pure JavaScript you'd do `meta.getAttribute("charset")` to get it's value. I guess you should do the same if you don't have react.

**Comment by chronoDave** [comment]
Ah, so am I then understanding correctly that attributes are not the same as properties (although a lot of the attributes seem to be properties as well)?

**Comment by saschanaz** [comment]
Yup, that is correct. You typically don't want to touch `charset` anyway in Javascript 😉

**Comment by chronoDave** [comment]
Thank you for the help and advice! I will close this issue now as my question has been answered
