### ISSUE TITLE
Wrong type of event "input"

### ISSUE THREAD

**Issue by aradzie** [microsoft/TypeScript-DOM-lib-generator#1227]
Interface `GlobalEventHandlersEventMap` defines type of event `"input"` as the generic `Event` interface.

```typescript
interface GlobalEventHandlersEventMap {
  // ...
  "beforeinput": InputEvent;
  "input": Event;
  // ...
}
```

Type of `"input"` should be `InputEvent`, the same as `beforeinput`.

Relevant links:

https://caniuse.com/?search=InputEvent
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event
https://w3c.github.io/uievents/#event-type-input
https://w3c.github.io/uievents/#event-type-beforeinput
https://w3c.github.io/uievents/tools/key-event-viewer.html

**Comment by saschanaz** [comment]
The issue is that `input` event does not always use `InputEvent`. See also #1174

**Comment by saschanaz** [comment]
Filed https://github.com/mdn/content/issues/11120 btw. Thank you for noticing that.

**Comment by saschanaz** [comment]
MDN triaged the issue, let's track it there.

**Comment by saschanaz** [comment]
@github-action close

**Comment by saschanaz** [comment]
@github-actions close
