### ISSUE TITLE
`Error` constructor has second argument

### ISSUE THREAD

**Issue by cawa-93** [microsoft/TypeScript-DOM-lib-generator#1238]
The `Error` constructor has signature `Error ( message [ , options ] )`
https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-error-message

But at the moment, trying to set `cause` or read `cause` leads to a type error. [Playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBApjAvDMcDuMCiAnbJsAUA5DntjALZwQQCGA5nEQDQwDeMwtArhHAFwwiRGAF8AlAFgAUKEggANnAB0CkPQIquvOOKA)

**Comment by yume-chan** [comment]
`Error` is a ECMAScript type, not form DOM spec, so see microsoft/TypeScript#45167

**Comment by everhardt** [comment]
If you set target to ES2022 it does work: https://www.typescriptlang.org/play?target=9#code/MYewdgzgLgBApjAvDMcDuMCiAnbJsAUA5DntjALZwQQCGA5nEQDQwDeMwtArhHAFwp0WXPmIBGAEwBmIgEoYAXzkBuALAAoUJBAAbOADpdIegUNdecOUA

**Comment by yume-chan** [comment]
@everhardt They were added in TypeScript 4.6.

**Comment by everhardt** [comment]
@yume-chan . Yes indeed. I don't get your point though, you still need to set `target` to `ES2022` to make it work right?

**Comment by yume-chan** [comment]
This issue was filed before TS 4.6 and `target: ES2022`. The information you provided is correct.
