### ISSUE TITLE
Native runtime type/interface checking - Feature Request

### ISSUE THREAD

**Issue by wmelton** [microsoft/TypeScript-DOM-lib-generator#1286]
For folks building services with a large majority of the data being handled coming from external data systems, much of the value of TypeScript for node.js wanes. 

There are very large and extremely well adopted projects like Zod and Runtypes that are closing this gap by extending the type checking to runtime. However, for those considering writing the next REST app in ts, especially if they're smaller orgs or new to ts, it can be overwhelming to have to learn ts conventions *and* a 3rd party library to get the benefits of type at runtime when working with dynamic data. 

I would love to see the roadmap include runtime checking available by default either as a tsconfig flag, or some lightweight syntax the compiler can use and understand. 

I understand their are likely difficulties with this, and reasons this hasn't been included before now, however, when you consider Zod has 500k/weekly npm downloads right now, I think its fair to say this is a need that is real and one that would help TypeScript be a no-brainer for many looking to make the switch. 

js+yup for runtime schema validation has to be subpar to the power of TypeScript if it was runtime aware, right?

**Comment by orta** [comment]
Thanks for the issue, but this idea goes against the [typescript design goals](https://github.com/microsoft/TypeScript/wiki/TypeScript-Design-Goals) and will likely never happen. That said, this is not the TypeScript repo (it's for the DOM types) - so you might want to check to see prior discussion on the main repo: https://github.com/microsoft/TypeScript
