### ISSUE TITLE
Add `RegExp.prototype.hasIndices`, `RegExpExecArray.indices`, and `RegExpMatchArray.indices`

### ISSUE THREAD

**Issue by Dragory** [microsoft/TypeScript-DOM-lib-generator#1289]
Original proposal: https://github.com/tc39/proposal-regexp-match-indices

MDN:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec#description

Implemented by major browsers: https://github.com/mdn/browser-compat-data/blob/06e29c8bf5c29869288b68d8d027ba34f76e5981/javascript/builtins/RegExp.json#L454

Also available in Deno and, despite not being listed in `mdn/browser-compat-data`, at least Node.js v16.12.0.

**Comment by saschanaz** [comment]
This should go microsoft/TypeScript as this repo does not cover JavaScript changes.

**Comment by Dragory** [comment]
Thank you! For anyone landing here from Google, there is an existing issue in the TypeScript repository here: https://github.com/microsoft/TypeScript/issues/44227
