### ISSUE TITLE
Missing `MediaTrackSettings.channelCount` and a few

### ISSUE THREAD

**Issue by compulim** [microsoft/TypeScript-DOM-lib-generator#1290]
From #1029, there are a few removed.

> - MediaTrackSettings
>    - Added: `restrictOwnAudio`
>    - Removed: `autoGainControl`, `channelCount`, `latency`, `noiseSuppression`, `resizeMode`

Comparing to the [Media Capture and Streams spec](https://www.w3.org/TR/mediacapture-streams/#dictionary-mediatracksettings-members), these are in the Candidate Recommendation Draft:

- `boolean autoGainControl`
- `long channelCount`
- `double latency`
- `boolean noiseSuppression`
- `DOMString resizeMode` of either [`none` or `crop-and-scale`](https://www.w3.org/TR/mediacapture-streams/#dom-videoresizemodeenum)

Should we add them back?

Side note, `restrictOwnAudio` is from the [Screen Capture spec](https://www.w3.org/TR/screen-capture/#extensions-to-mediatracksettings).

Another side note, there was a discussion #286 about some of them, that thread is 4.5 years old.

**Comment by HolgerJeromin** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/autoGainControl#browser_compatibility
This has only chromium support (removed in firefox 55). 
Every API needs at least two implementing engines to be added here...

**Comment by HolgerJeromin** [comment]
`autoGainControl` was readded in ts4.5 #1143

`resizeMode` has only chromium support.
Every API needs at least two implementing engines to be added here...

**Comment by compulim** [comment]
Thanks @HolgerJeromin for clarifying. I was not aware of the "two implementing engines" requirement.
