### ISSUE TITLE
HTMLDialogElement is deprecated and is missing properties and methods in lib.dom.d.ts

### ISSUE THREAD

**Issue by mmichlin66** [microsoft/TypeScript-DOM-lib-generator#1293]
From TypeScript 4.4, the HTMLDialogElement interface is deprecated with the comment *this is not available in most browsers* and is missing properties `open` and `returnValue` and methods `show()`, `showModal()` and `close()`. According to MDN, HTMLDialogElement interface and the indicated properties and methods are implemented in Chrome (and therefore in Edge and Opera) and Firefox and in their corresponding mobile versions. It is also in pre-release in Safari.

The `<dialog>` element and the corresponding HTMLDialogElement interface have long been implemented under the feature flag in Firefox and finally fully implemented in Firefox 98.

**Comment by HolgerJeromin** [comment]
This was fixed by #1259

**Comment by mmichlin66** [comment]
This was fixed by https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1259
