### ISSUE TITLE
AudioWorkletProcessor is missing required function

### ISSUE THREAD

**Issue by JelleInfinity** [microsoft/TypeScript-DOM-lib-generator#1298]
See: https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletProcessor/process

The documentation notes:
> Although the method is not a part of the [AudioWorkletProcessor](https://developer.mozilla.org/en-US/docs/Web/API/AudioWorkletProcessor) interface, any implementation of AudioWorkletProcessor must provide a process() method.

So to add this requirement I think it should be added to the interface. Like this:

```typescript
type AudioWorkletProcessorParamMap = { [key: string]: Float32Array };

interface AudioWorkletProcessor {
    readonly port: MessagePort;
    process(inputs: Float32Array[][], outputs: Float32Array[][], parameters: AudioWorkletProcessorParamMap): boolean;
}
```

**Comment by JelleInfinity** [comment]
@mathe42 What do you think? I'm not well versed in typescript yet

**Comment by mathe42** [comment]
Not sure should be decided by a maintainer. 

@saschanaz ?
