### ISSUE TITLE
Consider making the value argument of promises optional.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/TypeScript-DOM-lib-generator#1333]
I frequently pass in the promise callback argument into other functions that don't intend on providing any arguments in the callback function. For example:

```ts
async function doSomething() {
  // do something...
  await new Promise(r => setTimeout(r, 1000));
  // do something else...
}
```
admittedly this is a bit of a bad example, because setTimeout actually does provide an argument in its callback.
But consider the following:
```ts
function fireCallback(cb: () => void) {
    cb();
}

await new Promise(r => fireCallback(r));
//                                 ^^^------Argument of type '(value: unknown) => void'
//                                 is not assignable to parameter of type '() => void'.
```
<sup>[playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMGAnApgYQIYBtcBG2EA1gBQQEBciZAlIgLwB8iAbnDACYMDeAUIiGJK9ANz8Avv35h0Ad0QAFVHAC2MAM7oyqJqxQYc+IqV106EgPRXhd+w8dCAeq4C0HzwEFUAcxBq6GBQiHDAiFAAngAO6IgA5GRseCDoNOAkYHDyYAws7Jxc8fw2TmXlWohZIdiamjC+YNgEuHFQcIjR2KjYgVDoemERMXGJeawc3PEAdEA)</sup>

Passing in `r` in `fireCallback` gives an error because the promise expects `r` to be called with a value, even though this is perfectly valid in JavaScript. The promise will simply resolve with `undefined`.

One way to work around this is by simply doing `new Promise<void>(r => fireCallback(r))`, but this isn't possible when working with JavaScript in strict mode. So the workaround ends up looking more like this:
```js
/** @type {Promise<void>} */
const promise = new Promise(r => fireCb(r));
await promise;
```
<sup>[playground link](https://www.typescriptlang.org/play?ssl=11&ssc=16&pln=11&pc=29&filetype=js#code/PQKhCgAIUgBAHAhgJ0QW0gbwBQEpIC8AfJAG4D2AlgCYC+kAxgEZQjDgBmArgHYMAulcj0gdKyAKYBhJtmb5MUSMuZ4A3OFrhwiAM4BPPqN4ChI6uQDK5NBP4ALSjwDmeLEuXBgkC5F027RxcAOlDtZU8wOH59eAksAAVkG0pdCQAeChoiejYPRmFdfkh4ZLRU+IJIHgkAd0gklLTsZEISMUkZFtxcDQjIRFrESmLSpokNfK8fcj8AhydnSAkAGzTQ4M0gA)</sup>

which is really verbose and tedious to write.

The `PromiseConstructor` is currently defined as
```ts
new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
```
making `value:` optional like so:
```ts
new <T>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
```
solves this issue, but I'm not sure if it might break anything else.

**Comment by MartinJohns** [comment]
> making value: optional like so:

`T` does not include `undefined`, and you call `resolve` without an argument, then you get an invalid value.

**Comment by yume-chan** [comment]
1. `Promise` is part of JavaScript, not DOM, so this is not the right issue tracker.
2. the first argument of `resolve` is actually deliberately changed to be non-optional in TypeScript 4.1 (https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#resolves-parameters-are-no-longer-optional-in-promises) to prevent people from forgetting the argument.
3. I think the type inference should be improved, when you write `new Promise(r => setTimeout(r), 1000)`, the `T` in `Promise` should be whatever `setTimeout` will pass to it (or `void` if no argument given), if no better type can be inferred.

**Comment by jespertheend** [comment]
> `Promise` is part of JavaScript, not DOM, so this is not the right issue tracker.

Ah sorry about that, is the TypeScript repository the correct place for this?

**Comment by orta** [comment]
It is, yes, but given the switch is pretty recent and release notes worthy (with some good arguments for why I don't think the request is going to get too far.

**Comment by jespertheend** [comment]
Yeah me neither, I'll mostly aim for point 3 in https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1333#issuecomment-1144455905
My main issue is that

```js
/** @type {Promise<void>} */
const promise = new Promise(r => fireCb(r));
await promise;
```
is tedious to type.

**Comment by jespertheend** [comment]
I've submitted https://github.com/microsoft/TypeScript/issues/49390
