### ISSUE TITLE
[AudioWorklet] Missing properties in AudioParamMap interface

### ISSUE THREAD

**Issue by abritopach** [microsoft/TypeScript-DOM-lib-generator#1358]
According to official documentation:

https://webaudio.github.io/web-audio-api/

https://www.w3.org/TR/webaudio/#audioparammap

This interface has "entries", "forEach", "get", "has", "keys", "values", @@iterator methods and a "size" getter brought by readonly maplike.

<img width="1440" alt="Captura de pantalla 2022-07-05 a las 19 36 47" src="https://user-images.githubusercontent.com/2934069/177393752-10f75940-9bb0-40d3-b04a-31dd57a118af.png">

but in node_modules/typescript/lib/lib.dom.d.ts (https://www.npmjs.com/package/@types/audioworklet) we only have

<img width="802" alt="Captura de pantalla 2022-07-05 a las 19 37 40" src="https://user-images.githubusercontent.com/2934069/177393772-c63b8af3-3ce5-4b7e-a677-3dd296a3fb0d.png">

Is there any timeline for when this interface will be updated?

Thanks!

**Comment by saschanaz** [comment]
It's already ReadonlyMap: https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/17ff4cb6ec47eef6c361047aed35b2534411eb23/baselines/dom.iterable.generated.d.ts#L9

Perhaps your compilation target is es5, or your lib lacks `dom.iterable`?

**Comment by saschanaz** [comment]
I think changing `target` should fix your issue.

@github-actions close
