### ISSUE TITLE
Property `aspectRatio` does not exist on type CSSStyleDecleration

### ISSUE THREAD

**Issue by chintuyadavsara** [microsoft/TypeScript-DOM-lib-generator#1371]
Hi Team,

Even though `aspect-ratio` css property is hugely supported in all modern browsers. Its giving typescript error saying

**Property `aspectRatio` does not exist on type CSSStyleDecleration**
![image](https://user-images.githubusercontent.com/26032330/181477908-49ca7ed7-8dcb-4e3a-aff1-11e307c74bfe.png)

🔎 Search Terms
**CSSStyleDeclaration aspectRatio**

![image](https://user-images.githubusercontent.com/26032330/181477161-21597a59-a281-40f5-af13-bd1f953c8b4a.png)

Could you please address this issue.

Thank you

**Comment by mathe42** [comment]
It is defined here. 
https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.generated.d.ts#L2742

It was added more than 1 year ago... Do you use a old version of typescript?

**Comment by chintuyadavsara** [comment]
Thank you @mathe42 . Typescript version I'm using is 4.3

**Comment by saschanaz** [comment]
TS versions older than 4.4 are not supported, you can try upgrade to the latest version, or at least to 4.4 and deploy https://www.npmjs.com/package/@types/web.

@github-actions close
