### ISSUE TITLE
according to DOM specs cancelBubble is a legacy alias of .stopPropagation()

### ISSUE THREAD

**Issue by Ahmed-Hakeem** [microsoft/TypeScript-DOM-lib-generator#1384]
# lib Update Request

## Missing / Incorrect Definition

According to DOM spec cancelBubble is a legacy alias of .stopPropagation(), and after exploring library code this issue happened because of where the property value came from, It is read from the property deprecated value  from data.json (cancelBubble.__compact.status.deprecated) which is exported by @mdn/browser-compat-data v5.0.0, this value is read inside mapInterfaceLike function in src/build/bcd/mapper.ts

This issue has been resolved in @mdn/browser-compat-data starting from v5.1.9 inside 
commit: 36ffef821fafb429430f0286009787505a3ff000 

so I think it will be solved by only updating @mdn/browser-compat-data 

## Documentation Link

https://dom.spec.whatwg.org/#interface-event

## Reference 
https://github.com/microsoft/TypeScript/issues/50517

**Comment by saschanaz** [comment]
Fixed in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1394, thanks!

@github-actions close

**Comment by Ahmed-Hakeem** [comment]
> Fixed in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1394, thanks!
> 
> 
> 
> @github-actions close

It's my pleasure 😊❤️
