### ISSUE TITLE
incomplete FileSystemHandle types

### ISSUE THREAD

**Issue by jozefchutka** [microsoft/TypeScript-DOM-lib-generator#1393]
Please update types for File System Access API:

[FileSystemDirectoryHandle](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/85672cd2b4eeb2852897f05af1cfa8a5faa24974/baselines/sharedworker.generated.d.ts#L1449) is missing [entries/values iterators](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle)

[FileSystemFileHandle](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/85672cd2b4eeb2852897f05af1cfa8a5faa24974/baselines/sharedworker.generated.d.ts#L1463) missing [createWritable](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle)

[FileSystemHandle](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/85672cd2b4eeb2852897f05af1cfa8a5faa24974/baselines/sharedworker.generated.d.ts#L1474) is missing
[queryPermission and requestPermission](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemHandle)

**Comment by mathe42** [comment]
createWritable, queryPermission and requestPermission are not missing they are only supported in chromium so they are not added see for example https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createWritable#browser_compatibility

For [FileSystemDirectoryHandle](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/85672cd2b4eeb2852897f05af1cfa8a5faa24974/baselines/sharedworker.generated.d.ts#L1449) is missing [entries/values iterators](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle) on first I think you are right not 100% sure maybe that would just need a bump of the BCD version to be fixed...

**Comment by saschanaz** [comment]
> [FileSystemDirectoryHandle](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/85672cd2b4eeb2852897f05af1cfa8a5faa24974/baselines/sharedworker.generated.d.ts#L1449) is missing [entries/values iterators](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemDirectoryHandle)

This is because the generator does not support async iterable, but then as far as I know Blink is the only engine that supports this. I'm all for a PR for that part, though. (Hi @MattiasBuelens, do you want to try cherry-picking from #1135 for this?)

**Comment by MattiasBuelens** [comment]
`FileSystemDirectoryHandle` has async iterable support in Blink (as of [#1011539](https://bugs.chromium.org/p/chromium/issues/detail?id=1011539)) and WebKit (as of [#231142](https://bugs.webkit.org/show_bug.cgi?id=231142)). So this *does* satisfy our criteria! 😄 (I'm a bit surprised that `FileSystemDirectoryHandle` got support before `ReadableStream`, but okay. 😛)

I'll look into reworking #1135.

**Comment by ibillingsley** [comment]
Firefox supports FileSystemFileHandle.createWritable as of version 111.
https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility

**Comment by saschanaz** [comment]
#1521 fixed this. Blink-only permission things will probably not be added given other implementors are against them.

@github-actions close

**Comment by mrkev** [comment]
In what library is this included? The types for (listing the contents of a directory)[https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system#listing_the_contents_of_a_folder] seem to be missing for me, I'm using: `"lib": ["DOM", "DOM.Iterable", "ESNext"]`

<img width="593" alt="image" src="https://github.com/microsoft/TypeScript-DOM-lib-generator/assets/1285131/e0de3721-68c0-4ba8-b643-f2f106b33ca8">

**Comment by mrkev** [comment]
Created a new issue to not discuss in a closed issue https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1639
