### ISSUE TITLE
Web Codecs API Definitions

### ISSUE THREAD

**Issue by sinclairzx81** [microsoft/TypeScript-DOM-lib-generator#1404]
# Suggestion

Would be good to include the WebCodecs API as part of the TS DOM definitions https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API

## 🔍 Search Terms

AudioData AudioDecoder AudioEncoder EncodedAudioChunk EncodedVideoChunk ImageDecoder ImageTrack ImageTrackList VideoDecoder VideoEncoder VideoColorSpace VideoFrame

## ✅ Viability Checklist

My suggestion meets these guidelines:

* [x] This wouldn't be a breaking change in existing TypeScript/JavaScript code
* [x] This wouldn't change the runtime behavior of existing JavaScript code
* [x] This could be implemented without emitting different JS based on the types of the expressions
* [x] This isn't a runtime feature (e.g. library functionality, non-ECMAScript syntax with JavaScript output, new syntax sugar for JS, etc.)
* [x] This feature would agree with the rest of [TypeScript's Design Goals](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals).

## ⭐ Suggestion

Currently the definitions for this WebCodecs API are unrecognized and require custom definitions. Would be good to include them if possible.

## 📃 Motivating Example

Media streaming, Video and Audio encode / decode.

## 💻 Use Cases

Realtime Media Streaming

**Comment by guillaumebrunerie** [comment]
You can also simply install the following package: https://www.npmjs.com/package/@types/dom-webcodecs

**Comment by saschanaz** [comment]
Video related types are added by https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1514, remaining things will be added when browser engine implementations come. Use the @types package mentioned above if you need audio/image things before that.

@github-actions close
