### ISSUE TITLE
Add UserActivation interface to Navigator interface in lib.dom.d.ts

### ISSUE THREAD

**Issue by morganney** [microsoft/TypeScript-DOM-lib-generator#1417]
I'm using `tsc` 4.8.4 and there is no support for `navigator.userActivation`. This is now part of the HTML Living Standard and implemented by Chrome, Edge, and Opera browsers.

Spec: https://html.spec.whatwg.org/multipage/interaction.html#the-useractivation-interface
MDN: https://developer.mozilla.org/en-US/docs/Web/API/UserActivation

This is useful when writing JavaScript that interacts with Web API's that are [gated behind user interaction](https://developer.mozilla.org/en-US/docs/Web/Security/User_activation), such as the Web Speech API.

**Comment by mathe42** [comment]
Chrome, Edge and Opera are all chromium based so only 1 implementation but 2 are required for a feature to be added.

**Comment by morganney** [comment]
Ok, so the requirements for implementation of a spec sound like it must _not_ be an **experimental technology**  as [defined by MDN](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete#experimental).

For the record, that seems a little conservative, and makes it harder to adopt TypeScript when leveraging new technologies that have real world implementations (by the world's most popular browser).

**Comment by mathe42** [comment]
@morganney You can fork this and change here https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/src/build/bcd.ts#L17 that chrome count as 2 if you need that. And build it for your use.

**Comment by morganney** [comment]
> There are so many experimantal api out there you won't want to include all of them...

@mathe42 I can understand that stance. Like I alluded to, you are making it harder to use TypeScript while leveraging new tech that _does_ have real world implementations when you make that choice, however.

Thanks for the suggested help.

**Comment by saschanaz** [comment]
Fixed by #1514.

@github-actions close
