### ISSUE TITLE
Add method `static Response.json(data, init)`

### ISSUE THREAD

**Issue by regseb** [microsoft/TypeScript-DOM-lib-generator#1444]
Hi,

A new method has been added: [**`static Response.json(data, init)`**](https://fetch.spec.whatwg.org/#dom-response-json) to create a response that contains JSON (not to be confused with [`Response.prototype.json()`](https://fetch.spec.whatwg.org/#dom-body-json)).

- https://github.com/whatwg/fetch/issues/1389
- https://github.com/whatwg/fetch/pull/1392

```typescript
declare var Response: {
    // ...
    json(data: any, init?: ResponseInit): Response;
};
```
Support:

- :heavy_check_mark: Chromium [105](https://chromestatus.com/feature/5197912798658560)
- :x: Firefox: [_Implement `Response.json` static method_](https://bugzil.la/1758943) / [_D171217_](https://phabricator.services.mozilla.com/D171217)
- :x: Safari: [_Implement `Response.json` static method_](https://webkit.org/b/240375) / https://github.com/WebKit/WebKit/pull/10593
- :heavy_check_mark: Node via [Undici v5.3.0](https://github.com/nodejs/undici/releases/tag/v5.3.0)
  - node-fetch [v3.3.0](https://github.com/node-fetch/node-fetch/releases/tag/v3.3.0)
- :heavy_check_mark: Deno [1.22](https://deno.com/blog/v1.22#new-responsejson-static-method)
- :heavy_check_mark: Bun [0.0.74](https://github.com/oven-sh/bun/commit/394ec8dcbc862eaab7239c8592613c99f3eb87cd)

---

I found that in this project:

https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/513aae273e24603cdc14216e2d4111be96c8e564/inputfiles/removedTypes.jsonc#L83-L95

**Comment by karlhorky** [comment]
@regseb Now that #1462 has been closed and [the `Response.json()` types will show up in TS 5.2](https://github.com/microsoft/TypeScript/issues/52841#issuecomment-1574002759), maybe this can be closed?
