### ISSUE TITLE
@types/sharedworker errors starting version 0.0.86

### ISSUE THREAD

**Issue by dawidbojarowicz** [microsoft/TypeScript-DOM-lib-generator#1455]
Hey,

The changes done in 0.0.86 are causing build errors.

https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/00230f71f372e921bc340eaf491301cbddd6d5aa#diff-990e060f79cb4010eee21df7a07f2d564ad62207d12568874c986296c3ad01d8R1091

```
ERROR in \node_modules\@types\sharedworker\index.d.ts
[tsl] ERROR in \node_modules\@types\sharedworker\index.d.ts(1004,19)
      TS1110: Type expected.

ERROR in \node_modules\@types\sharedworker\index.d.ts
[tsl] ERROR in \node_modules\@types\sharedworker\index.d.ts(1005,1)
      TS1128: Declaration or statement expected.
```
      
The error is related to below code:

```
interface Crypto {
    /** Available only in secure contexts. */
    readonly subtle: SubtleCrypto;
    getRandomValues<T extends ArrayBufferView | null>(array: T): T;
    /** Available only in secure contexts. */
    randomUUID(): `${string}-${string}-${string}-${string}-${string}`;
}
```
      
@HarryAllen1 @saschanaz would it be possible for you to have a look on it?

**Comment by saschanaz** [comment]
Are you running TS 4.0.x? It seems only 4.1+ supports the syntax. (And the official minimum support is 4.4)

**Comment by dawidbojarowicz** [comment]
Thanks @saschanaz , your suggestion helped!
