### ISSUE TITLE
Add FileSystemSyncAccessHandle

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/TypeScript-DOM-lib-generator#1471]
The `FileSystemFileHandle.prototype.createSyncAccessHandle` method is used to create and object to synchronously read from and write to a file. It is only available in Web Workers.

MDN Link: https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileHandle/createSyncAccessHandle

![caniuse](https://user-images.githubusercontent.com/23744935/212119963-b8f90402-016c-4f31-af73-ea716c73b3e4.png)

It is already supported by two or more browser engines (Chrome & Safari). Adding the FileSystemSyncAccessHandle api to  `lib.webworker.d.ts` would be a great addition.

**Comment by saschanaz** [comment]
Added by #1424 last year. Maybe update your TypeScript version?

**Comment by SimonSiefke** [comment]
That's it. It is supported in TypeScript 5.0.0-beta. Thank you!

**Comment by namse** [comment]
Still got error `Property 'createSyncAccessHandle' does not exist on type 'FileSystemFileHandle'.ts(2339)` on typescript 5.4.5

**Comment by saschanaz** [comment]
You need to make sure your worker script is using the right tsconfig; you need to specify `"lib": ["webworker", ...]`

**Comment by namse** [comment]
Problem solved. Thank you!
