### ISSUE TITLE
**Describe the feature**

### ISSUE THREAD

**Issue by chanya2534** [microsoft/TypeScript-DOM-lib-generator#1485]
**Describe the feature**

Convert .deb to .ipa if it's application package automatically on install. 

_Originally posted by @vadim-a-yegorov in https://github.com/vadim-a-yegorov/TrollStore/issues/2_

**Comment by vadim-a-yegorov** [comment]
You good? lmao

**Comment by saschanaz** [comment]
@github-actions close
