### ISSUE TITLE
createImageBitmap() `imageOrientation` option type incorrect in 5.0.0-beta

### ISSUE THREAD

**Issue by frank-weindel** [microsoft/TypeScript-DOM-lib-generator#1507]
# lib Update Request

## Configuration Check

My compilation *target* is `ES2022` and my *lib* is `the default`.

## Missing / Incorrect Definition

In 5.0.0-beta the DOM provided [createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap) (MDN linked) function is not allowing the string "none" to be set on the `imageOrientation` option property.

It should be allowing the strings `"flipY" | "none"` according to MDN (and does work in previous TS versions) but in 5.0.0-beta the only strings allowed are: `"flipY" | "from-image"`.

`"from-image"` seems to be coming from a related but separate CSS property called [`image-orientation`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation).

**node_modules/typescript/lib/lib.dom.d.ts**:
```ts
// ...
interface ImageBitmapOptions {
    colorSpaceConversion?: ColorSpaceConversion;
    imageOrientation?: ImageOrientation;
    premultiplyAlpha?: PremultiplyAlpha;
    resizeHeight?: number;
    resizeQuality?: ResizeQuality;
    resizeWidth?: number;
}
// ...
declare function createImageBitmap(image: ImageBitmapSource, options?: ImageBitmapOptions): Promise<ImageBitmap>;
declare function createImageBitmap(image: ImageBitmapSource, sx: number, sy: number, sw: number, sh: number, options?: ImageBitmapOptions): Promise<ImageBitmap>;
// ...
type ImageOrientation = "flipY" | "from-image";
// ...
```

## Sample Code

Sample:
```ts
createImageBitmap({} as ImageBitmap, {
    imageOrientation: 'none'
 // ^^^^^^^^^^^^^^^^ Type '"none"' is not assignable to type 'ImageOrientation | undefined'.(2322)
});
```

[Playground Link](https://www.typescriptlang.org/play?target=9&ts=5.0.0-beta#code/MYJwpghgLmCSC2EDmYBCBLKiAOAKA3gL4AEEAzsQsmpjgDTH4BQxrx6iKA8iOmAHZRo6APb8AXMQDk-MWClNCASgDcTJkA)

## Documentation Link

https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap

**Comment by saschanaz** [comment]
Hmm, the spec renamed `none` to `from-image` in https://github.com/whatwg/html/pull/8710. That said:

* Gecko: Has `from-image` but still allows and defaults to `none` https://searchfox.org/mozilla-central/rev/e53063b2628e6e23d35ad1f7d786ab1a361051b7/dom/webidl/ImageBitmap.webidl#390,396
* WebKit: Does not have `from-image` and defaults to `none https://searchfox.org/wubkat/rev/5b368793a8c0a3d99c6991fcd3ef96e3dbd2cf2a/Source/WebCore/html/ImageBitmapOptions.idl#26,32
* Blink: Has `from-image` and defaults to `from-image`: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/imagebitmap/image_bitmap_options.idl;l=12;drc=9e618bcba212f7c43273c8c241298b0278d99bb6

Perhaps it's worth restoring `none` for the short term? I pinged MDN in https://bugzilla.mozilla.org/show_bug.cgi?id=1809740#a4470354_473060

**Comment by frank-weindel** [comment]
Seems reasonable to me that `none` should be allowed with maybe some documentation describing this transition period the browsers are slowly working through.

**Comment by frank-weindel** [comment]
@saschanaz Seems reasonable to me that none should be allowed with maybe some documentation describing this transition period the browsers are slowly working through.
