### ISSUE TITLE
HTMLInputElement readOnly => readonly

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript-DOM-lib-generator#1522]
Error TS2551

>Property readonly does not exist on type HTMLInputElement. Did you mean 'readOnly'?

`readOnly` and `readonly` are used interchangeably/inconsistently due to HTML and JS diverging:
https://html.spec.whatwg.org/multipage/input.html#the-readonly-attribute
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly#specifications
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement#readonly

I think allowing both would make sense?

**Comment by HolgerJeromin** [comment]
> I think allowing both would make sense?

The files of this project do not change the reality. They describe it.

Note the difference in HTML attribute (lowercase in spec but case **insensitive**) and DOM element (camelCase only) behaviour:
Tested in devTools:
```
> document.createElement('input').readOnly
false
> document.createElement('input').readonly
undefined
> let inputElm = document.createElement('input')
undefined
> inputElm.readOnly
false
> inputElm.setAttribute('readonly', '')
undefined
> inputElm.readOnly
true
> inputElm.removeAttribute('rEadOnLy')
undefined
> inputElm.readOnly
false
