### ISSUE TITLE
Property 'showPicker' does not exist on type 'HTMLInputElement'

### ISSUE THREAD

**Issue by prakhathi-m** [microsoft/TypeScript-DOM-lib-generator#1540]
Reference: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/showPicker

showPicker method on HTMLInputElement displays the browser picker for an input element.

I have been using date input and I have a customized calendar icon and on click of it, I need to open the datepicker. However, the code is used works well in browser but it throws a compilation error.

```
const input = document.getElementById('dateInput') as HTMLInputElement;
try {
  input.showPicker();
} catch (error) {
      window.alert(error);
}
```

` error TS2339: Property 'showPicker' does not exist on type 'HTMLInputElement'.`

**Comment by HolgerJeromin** [comment]
Do you have an old typescript?

This works in playground:

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAlmADgV1gXhgExMZBbAUzCgDpgAnAgQygIFEAbAw4gCgHIEUp2BKAbgBQUcgE8YAb0Ex4SVCQgALEAHcACnGABrAuVYDBAXxjAawRTFa7yIcr0nSZTlQmwqSVJuShXyNu0KGQA

**Comment by prakhathi-m** [comment]
Thanks, yes, I was using the older version of Typescript.
