### ISSUE TITLE
incomplete FontFaceSet inteface

### ISSUE THREAD

**Issue by jozefchutka** [microsoft/TypeScript-DOM-lib-generator#1555]
Please enhance [FontFaceSet](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.generated.d.ts#L8503) with [add()](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/add), there might be some more missing like clear/delete...

**Comment by HolgerJeromin** [comment]
This works in playground:

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZuWBeGYCmB3GAxR2CGwaAFAEQCyAnrmFKQDQykCuATgDbEC21iAdBhBw4AJgCUpMQG4AsACgAJiGDMuaWnwS0IffAoXEtUaUA

Do you have an old version running?
