### ISSUE TITLE
Array.prototype.filter( Boolean ) has incorrect return type

### ISSUE THREAD

**Issue by kkmuffme** [microsoft/TypeScript-DOM-lib-generator#1576]
https://www.typescriptlang.org/play?#code/FAMwrgdgxgLglgewgAhAhAKZBnApjeCAc2wC5kAlXKBAJwBMAebGWuYgGh1faIB8IYADZCAfMgCU5Fm2IBtALrAA3sACQtfGFoo5OfIRIA6eggC2AQ3YBGLngK9sJ81YgAmOwcfPL7AMyeDsROpr4QACyBhiEu7ACsUd6hrgBsicE+rgDs6cbJ7AAcuTFhAJzFmTYADMgKRiBwQjC4tFgAQuhCuBYoEgDcwAC+wEA

```
function foo( settings: Record<string, string|null> ): string[]
{
	return [ settings.domain1, settings.domain2, settings.domain3, settings.domain4, settings.domain5, settings.domain6, settings.domain7, settings.domain8, settings.domain9, settings.domain10 ].filter( Boolean );
}
```

`.filter( Boolean )` will remove all falsy elements from the array.

**Comment by orta** [comment]
You're looking for https://github.com/microsoft/TypeScript/issues/16655
