### ISSUE TITLE
Missing iterators for `FileSystemDirectoryHandle`

### ISSUE THREAD

**Issue by mrkev** [microsoft/TypeScript-DOM-lib-generator#1639]
The File System Access API is missing the types necessary to iterate through its entries (`.keys()`/`.values()`/`.entries()`).

Info on MDN: https://developer.mozilla.org/en-US/docs/Web/API/File_System_API/Origin_private_file_system#listing_the_contents_of_a_folder

Previous issue https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1393

Using:
```
typescript: "5.2.2"

// tsconfig.json
"lib": ["DOM", "DOM.Iterable", "ESNext"]
```

<img width="593" alt="image" src="https://github.com/microsoft/TypeScript-DOM-lib-generator/assets/1285131/e0de3721-68c0-4ba8-b643-f2f106b33ca8">

<img width="809" alt="image" src="https://github.com/microsoft/TypeScript-DOM-lib-generator/assets/1285131/56c9e7d1-96e3-4ef9-a3f4-337910425a1a">

**Comment by saschanaz** [comment]
You need to add "dom.asynciterable" too, or just set `target: esnext`.

**Comment by tebuevd** [comment]
> You need to add `dom.asynciterable` too, or just set `target: esnext` without explicit `lib`.

Didn't seem to work for me

<img width="986" alt="image" src="https://github.com/microsoft/TypeScript-DOM-lib-generator/assets/3241533/0dcb6aaf-a475-4374-84b6-377e6fb262a6">
<img width="600" alt="image" src="https://github.com/microsoft/TypeScript-DOM-lib-generator/assets/3241533/2628e541-2672-43d7-958f-17bac95e6b3d">

**Comment by saschanaz** [comment]
Because you made a big typo there. 😅

**Comment by tebuevd** [comment]
> Because you made a big typo there. 😅

😅
do you mean `ESNEXT.AsyncIterable`? I know you mentioned `dom.asynciterable`, but I don't think that option exists: https://www.typescriptlang.org/tsconfig#lib

I also tried with `target: ESNEXT` and it also didn't work

If the typo is something else, please let me know :)

**Comment by saschanaz** [comment]
Oops, you are right! Someone needs fix https://github.com/microsoft/TypeScript/issues/29867 and make it include https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.asynciterable.generated.d.ts.

**Comment by tebuevd** [comment]
Thank you for the explanation @saschanaz ! As workaround, I've added the following code from the linked PR in a declaration file in my repo:

async-iterator.d.ts
```
/////////////////////////////
/// Window Async Iterable APIs
/////////////////////////////

interface FileSystemDirectoryHandle {
  [Symbol.asyncIterator](): AsyncIterableIterator<[string, FileSystemHandle]>;
  entries(): AsyncIterableIterator<[string, FileSystemHandle]>;
  keys(): AsyncIterableIterator<string>;
  values(): AsyncIterableIterator<FileSystemHandle>;
}
```
