### ISSUE TITLE
"letterSpacing" not defined in interface CanvasTextDrawingStyles (CanvasRenderingContext2D)

### ISSUE THREAD

**Issue by bjornbacklund** [microsoft/TypeScript-DOM-lib-generator#1644]
### 🔎 Search Terms

letterSpacing CanvasTextDrawingStyles CanvasRenderingContext2D

### 🕗 Version & Regression Information

Have not tested in other versions than C:\Program Files (x86)\Microsoft SDKs\TypeScript\4.9\lib.dom.d.ts

### 🙁 Actual behavior

"letterSpacing" not defined in interface CanvasTextDrawingStyles 

### 🙂 Expected behavior

"letterSpacing" defined in interface CanvasTextDrawingStyles 

### Additional information about the issue

letterSpacing: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/letterSpacing

**Comment by saschanaz** [comment]
Fixed by #1612.

**Comment by saschanaz** [comment]
@github-actions close
