### ISSUE TITLE
IntersectionObserverEntry: rootBounds property is never null

### ISSUE THREAD

**Issue by jayfz** [microsoft/TypeScript-DOM-lib-generator#1694]
Hi!

The `IntersectionObserverEntry` interface in `lib.dom.d.ts` includes `rootBounds` definition as `DOMRectReadOnly | null`. However while reading MDN documentation and based on my own experimentation it seems this property is never null. It either represents the bounds of the root element or the viewport's.

[MDN documentation link](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry/rootBounds).

> A [DOMRectReadOnly](https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly) which describes the root intersection rectangle. For roots which are the [Document](https://developer.mozilla.org/en-US/docs/Web/API/Document)'s viewport, this rectangle is the bounds rectangle of the entire document. Otherwise, it's the bounds of the root element.

Current behavior:
```typescript
readonly rootBounds: DOMRectReadOnly | null;
```
Expected behavior
```typescript
readonly rootBounds: DOMRectReadOnly;
```

Thank you.

**Comment by RyanCavanaugh** [comment]
The spec seems to describe when it's null:

> rootBounds, of type [DOMRectReadOnly](https://drafts.fxtf.org/geometry-1/#domrectreadonly), readonly, nullable
For a [same-origin-domain target](https://w3c.github.io/IntersectionObserver/#intersectionobserver-same-origin-domain-target), this will be the [root intersection rectangle](https://w3c.github.io/IntersectionObserver/#intersectionobserver-root-intersection-rectangle). Otherwise, this will be null.

**Comment by jayfz** [comment]
You are right! Thanks for pointing that out. That's a corner case I didn't consider.
