### ISSUE TITLE
`String.prototype.charCodeAt` accepts `undefined`

### ISSUE THREAD

**Issue by mollthecoder** [microsoft/TypeScript-DOM-lib-generator#1707]
Take the following example:
```ts
"Hello, world!".charCodeAt();
```
This is safe, because `undefined` is automatically converted to zero. It is equivalent to this:
```ts
"Hello, world!".charCodeAt(0);
```
Or this:
```ts
"H".charCodeAt(0);
```
However, it is currently marked as a required argument.

**Comment by HolgerJeromin** [comment]
Would that change be only spec conform or really useful? 
I think many/some calls with variables with undefined are bugs/unintentional.

**Comment by saschanaz** [comment]
This should go https://github.com/microsoft/TypeScript as the code resides there.

**Comment by RyanCavanaugh** [comment]
This is the intended behavior.
