### ISSUE TITLE
NotificationOptions is missing image option

### ISSUE THREAD

**Issue by MathMan05** [microsoft/TypeScript-DOM-lib-generator#1749]
https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification
There is an option for an image on the notification API, and NotificationOptions is missing a property for it. (sorry, I'm new to TS, I'm not sure what all to include)

**Comment by cpplearner** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/Notification/image, `image` is not supported by Firefox and Safari.

So it doesn't meet the condition in the [README](https://github.com/microsoft/TypeScript-DOM-lib-generator?tab=readme-ov-file#why-is-my-fancy-api-still-not-available-here), which says:

> A feature needs to be supported by two or more major browser engines to be included here, to make sure there is a good consensus among vendors: __Gecko__ (Firefox), __Blink__ (Chrome/Edge), and __WebKit__ (Safari).

**Comment by MathMan05** [comment]
Ok, sorry for bothering y'all then
