### ISSUE TITLE
`Array.isArray` does not recognize `readonly` arrays

### ISSUE THREAD

**Issue by GauBen** [microsoft/TypeScript-DOM-lib-generator#1793]
Hi TS team! I'm having an issue with the type of `Array.isArray`:

```ts
declare const x: readonly number[]

if (Array.isArray(x)) {
    let y = x[0]
     // ^? let y: any
}
```

[Playground](https://www.typescriptlang.org/play/?ssl=6&ssc=2&pln=1&pc=1#code/CYUwxgNghgTiAEYD2A7AzgF3gDwFzzimFQgE94UBXAWwCMQYBtAXQChWBLAM3gAoBBGDCikAdBzSDhpXtgCUc+AG9W8NfAggs5ALw5GABjbq1AelPwAegH5WAX3ahIsBMnRYJUkQCZ8s-FAopIo6AHw48BLwgaQs8AA+BCBEJOQxLOzcfJ5CPrIKyqrqmtrwetiGxibmVrZ2QA)

I'm willing to open a PR if the fix is as I suggest in the playground above

**Comment by orta** [comment]
This is the wrong repo (this is for the DOM types) but you're looking at an incredibly deep rabbit hole if you want to try solve that, you can start based on links in one of my best attempts a few years back: https://github.com/microsoft/TypeScript/pull/42316
