### ISSUE TITLE
Missing properties on CSSStyleDeclaration in upstream TypeScript

### ISSUE THREAD

**Issue by rishipal** [microsoft/TypeScript-DOM-lib-generator#1826]
We're seeing a deprecation error in our tooling when someone tries to use the property `webkitLineClamp` in their code. Error: 

```
webkitLineClamp is deprecated: This is a legacy alias of `lineClamp`.
``` 

I checked that the property is defined in https://fossies.org/linux/TypeScript/src/lib/dom.generated.d.ts and is marked @deprecated. 

```
...
 4900     /**
 4901      * @deprecated This is a legacy alias of `lineClamp`.
 4902      *
 4903      * [MDN Reference](https://developer.mozilla.org/docs/Web/CSS/-webkit-line-clamp)
 4904      */
 4905     webkitLineClamp: string;
...
```

1. Why is this property (and others) not a part of TypeScript's definition of CSSStyleDeclaration interface in the lib.dom.d.ts file? Instead I see an ~empty definition of CSSStyleDeclaration in the [dom.iterable.generated.d.ts](https://github.com/microsoft/TypeScript/blob/40caf3431986884b3da7a607de22ced5d364d9fc/src/lib/dom.iterable.generated.d.ts#L40) file instead. Am I mistaken to think this property should exist in lib.dom.d.ts? 
2. Even if the property gets defined in the right place in the future, it will be deprecated. So which property should we use instead? I don't see any property named lineClamp defined anywhere in either of the two .d.ts files in TypeScript.

**Comment by saschanaz** [comment]
It's in dom.generated.d.ts, without iterable. That said, this should probably not have the deprecation mark, as nobody implemented lineClamp.
