### ISSUE TITLE
Missed `Screen` parent type (`EventTarget`)

### ISSUE THREAD

**Issue by turansky** [microsoft/TypeScript-DOM-lib-generator#1845]
[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Screen)

IDL
![Image](https://github.com/user-attachments/assets/89f8f84c-c2d7-4a9c-8471-6b66dca24398)

**Comment by saschanaz** [comment]
Are you sure you got the right IDL? https://drafts.csswg.org/cssom-view/#the-screen-interface

**Comment by saschanaz** [comment]
Eh, actually, that's Blink-only extension that is violating the IDL, as described here: https://w3c.github.io/window-management/#issue-288178db

>Make [Screen](https://drafts.csswg.org/cssom-view-1/#screen) derive from [EventTarget](https://dom.spec.whatwg.org/#eventtarget) in [CSSOM View § 4.3 The Screen Interface](https://drafts.csswg.org/cssom-view-1/#the-screen-interface).

**Comment by saschanaz** [comment]
This will be fixed if the API gets more implementation and the spec gets fixed.

@github-actions close
