### ISSUE TITLE
Unable to override a non-optional property with an optional one

### ISSUE THREAD

**Issue by rotemdan** [microsoft/TypeScript-DOM-lib-generator#191]
I'm trying to override:
```ts
interface SpeechSynthesisEvent extends Event {
    readonly charIndex: number;
    readonly elapsedTime: number;
    readonly name: string;
    readonly utterance: SpeechSynthesisUtterance | null;
}
```
With:
```ts
interface SpeechSynthesisEvent extends Event {
    readonly charIndex?: number;
    readonly elapsedTime?: number;
    readonly name?: string;
    readonly utterance: SpeechSynthesisUtterance | null;
}
```
So far the best I could do was:
```ts
interface SpeechSynthesisEvent extends Event {
    readonly charIndex: number | undefined;
    readonly elapsedTime: number | undefined;
    readonly name: string | undefined;
    readonly utterance: SpeechSynthesisUtterance | null;
}
```
But I'm not sure if that conforms well to the style of the rest of the type definitions. I've tried several approaches but none of them worked:

* Trying to override the property names modified with`?` in `overridingTypes.json` didn't do anything.
* Redefining the entire interface in `addedTypes.json` simply created a duplicate.
* Trying to remove the original in `removedTypes.json` didn't do anything.

Is there any way to achieve this? Any ideas?

**Comment by saschanaz** [comment]
`"optional": true` is the way to do this.

@github-actions close
