### ISSUE TITLE
"elements" missing from HTMLFieldSetElement

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-DOM-lib-generator#230]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement#Specifications

```typescript
// "Property 'elements' does not exist on type 'HTMLFieldSetElement'."
HTMLFieldSetElement.prototype.elements;

// (property) HTMLFormElement.elements: HTMLFormControlsCollection
// Retrieves a collection, in source order, of all controls in a given form.
HTMLFormElement.prototype.elements;
```

(https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement#Specifications)

it should probably be `HTMLFormControlsCollection` like the one in `HTMLFormElement`

**Comment by mhegazy** [comment]
PRs welcomed. You can find more information about contributing lib.d.ts fixes at https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#contributing-libdts-fixes.

**Comment by saschanaz** [comment]
Fixed by #462

@github-actions close

**Comment by DiceMasters** [comment]
Same with `target.value`

**Comment by HolgerJeromin** [comment]
> Same with target.value

@DiceMasters 
Can you explain more? Better to open an new issue for better visibility.
