### ISSUE TITLE
Element add/removeEventListener using specifies old API only

### ISSUE THREAD

**Issue by nhardy** [microsoft/TypeScript-DOM-lib-generator#273]
It looks like `Element` and all types that inherit from it specify the old `addEventListener`/`removeEventListener` APIs with `useCapture?: boolean` instead of the newer `options?: boolean | AddEventListenerOptions`/`options?: boolean | EventListenerOptions` that does appear on `EventTarget`.

**Comment by saschanaz** [comment]
Dupe of #174 which has been fixed

@github-actions close
