### ISSUE TITLE
Boolean is missing toString() method

### ISSUE THREAD

**Issue by DaSchTour** [microsoft/TypeScript-DOM-lib-generator#322]
According to https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Boolean/toString and linked specifications all browsers have a toString() method on booleans. But current version of lib.d.ts only includes the valueOf() method.

**Comment by saschanaz** [comment]
I remember I filed a similar issue long ago. `toString()` is hidden by default but you still can use it. (It's from Object interface)

**Comment by DaSchTour** [comment]
Oh, okay. Well I didn't even try, because I my IDE didn't offer it. So is this a bug in IntelliJ or maybe the typescript language service?

**Comment by mhegazy** [comment]
We do not expose the `Object` properties in completions by design. having them just produces noise for all completions, and we have found users seldom use them. It is still legal, and you should get signature help if you use them, but they are not shown in the completion list.

**Comment by saschanaz** [comment]
Let's track this on main TS repo.

@github-actions close
