### ISSUE TITLE
Invalid required types in `HTMLEmbedInterfaces` and `GetSvgDocument`

### ISSUE THREAD

**Issue by demurgos** [microsoft/TypeScript-DOM-lib-generator#355]
The [HTMLEmbedInterface](https://github.com/Microsoft/TypeScript/blob/ac7b87cabee6c0c12d9cffa30226f1314dff778b/lib/lib.dom.d.ts#L4726-L4777) defines some properties as required when they are in fact optional.

The following code returns the properties declared in the interface that are in fact missing:
```javascript
const embed = document.createElement("embed");
const keys = ["height", "hidden", "msPlayToDisabled", "msPlayToPreferredSourceUri", "msPlayToPrimary", "msPlayToSource", "name", "palette", "pluginspage", "readyState", "src", "units", "width"]
keys.filter(k => embed[k] === undefined)
// Array [ "msPlayToDisabled", "msPlayToPreferredSourceUri", "msPlayToPrimary", "msPlayToSource", "palette", "pluginspage", "readyState", "units" ]
```
(tested on latest Firefox and Chromium)

The following properties should be marked as optional:
- msPlayToDisabled
- msPlayToPreferredSourceUri
- msPlayToPrimary
- msPlayToSource (even if it is `any`, it may be better to mark it as optional for semantics)
- palette
- pluginspage
- readyState
- units

There is also a problem with the `getSVGDocument` method inherited from `GetSvgDocument`. According to [the spec](https://www.w3.org/TR/SVG/single-page.html#struct-InterfaceGetSVGDocument) and tests, this mays return null. Instead of  `getSVGDocument(): Document;`, this method should be typed as `getSVGDocument(): Document | null;`

**Comment by demurgos** [comment]
After checking [the spec for `<embed>`](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-embed-element) it seems that `getSVGDocument` can is optional for `HTMLEmbedElement`.

You can fix it either by extending `Partial<GetSvgDocument>` or defining the `getSVGDocument` method directly on `HTMLEmbedElement`.

**Comment by saschanaz** [comment]
#606

@github-actions close
