### ISSUE TITLE
How to override extending targets of the interface

### ISSUE THREAD

**Issue by falsandtru** [microsoft/TypeScript-DOM-lib-generator#50]
How can I override extending targets of the interface?
https://github.com/Microsoft/TSJS-lib-generator/pull/51/files#diff-02015aece7bbbd0234e4c3c785287c1cR884

**Comment by zhengbli** [comment]
It is not supported yet, but I'll try to make it available soon. Thank you for pointing out.

**Comment by falsandtru** [comment]
Thank you. I want to apply my fixes to the next version 1.8.
