### ISSUE TITLE
Create ServiceWorker lib

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#505]
Service workers basically extends from general worker but has their own types e.g. Client, ExtendableEvent, FetchEvent, etc. Will you accept a PR for this?

**Comment by mhegazy** [comment]
Yes, see https://github.com/Microsoft/TypeScript/issues/11781

**Comment by 13rac1** [comment]
A related issue for others who find this issue: Service Worker types were added by @saschanaz in #439

**Comment by HolgerJeromin** [comment]
CC @jakearchibald and @MattiasBuelens

**Comment by saschanaz** [comment]
#1034 

@github-actions close
