### ISSUE TITLE
Added method overload signatures are not placed in the right order

### ISSUE THREAD

**Issue by zhengbli** [microsoft/TypeScript-DOM-lib-generator#54]
Related to #53.

Ideally the added method overload signatures should be placed right before the most generic one, instead of at the end of the interface body.

**Comment by saschanaz** [comment]
This now works correctly. Specifically, the added signatures are processed before the existing signature.

https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/cef584baf82ae2ab55609c8816d791bee36d1dcf/src/build/emitter.ts#L966-L969

**Comment by saschanaz** [comment]
@github-actions close
