### ISSUE TITLE
document.fullscreenElement gone

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript-DOM-lib-generator#551]
`interface Document` used to define a property `readonly fullscreenElement: Element | null;`. It looks like as of Microsoft/TypeScript#25944 this property is missing. It doesn't seem to be deprecated so maybe it should be added back?
Detected in `vast-client` on DefinitelyTyped.

**Comment by andy-ms** [comment]
`document.onfullscreenchange` and `document.documentElement.requestFullscreen` are gone too, although browser compatibility for those isn't as good. Detected in `w3c-screen-orientation` on DefinitelyTyped.

**Comment by andy-ms** [comment]
This doesn't seem to be fixed in `typescript@3.1.0-dev.20180804` -- `document.fullscreenElement` is still a compile error.

**Comment by magcius** [comment]
The PR added the events and methods back but not the property.

**Comment by magcius** [comment]
PR attached.

**Comment by saschanaz** [comment]
@github-actions close
