### ISSUE TITLE
WindowOrWorkerGlobalScope should extend GlobalFetch

### ISSUE THREAD

**Issue by andy-ms** [microsoft/TypeScript-DOM-lib-generator#552]
Since it redeclares `fetch(input: RequestInfo, init?: RequestInit): Promise<Response>;`.
Or `GlobalFetch` could be removed since it's only used as a supertype of `Window` which already implements `WindowOrWorkerGlobalScope` anyway.

**Comment by saschanaz** [comment]
GlobalFetch has been removed from the spec, so yes, it should be removed.

I'll submit a patch aftec #546 is merged.

**Comment by mhegazy** [comment]
#546 will need some legal work too since it adds a new copyright notice, and we need to get MS lawyers to look at it. so it will take some time.

**Comment by saschanaz** [comment]
GlobalFetch is not there anymore

@github-actions close
