### ISSUE TITLE
window.opener should not be readonly

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/TypeScript-DOM-lib-generator#577]
Reposting https://github.com/Microsoft/tslint-microsoft-contrib/issues/293 here:

https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

If you use window.open then you must do this:

```typescript
let newWnd = window.open();
newWnd.opener = null;
```

For example, Monaco has to `any` cast around this:

https://github.com/Microsoft/vscode/blob/d01d178b3b7792d8bc91c03493d5be76b9c4eae8/src/vs/base/browser/dom.ts#L1146

However, `opener` is marked as `readonly`. It should not be.

**Comment by Paril** [comment]
This does not appear to be an issue in the current state of the code.

**Comment by saschanaz** [comment]
@github-actions close
