### ISSUE TITLE
Repo maintenance updates

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/TypeScript-DOM-lib-generator#582]
There's been a bit of a gap in work on this repository, so thanks everyone for being patient and understanding. We've had some shifting around over the last few months, but here's an update on what we're planning for the short term.

* [x] Update the TypeScript repo with current contents
* [ ] Pull in existing PRs
* [x] Snap a release by ~~end of October~~ beginning of November for new APIs and breaking changes; only minor fixes go in after that for 3.2.
* [ ] Triage existing issues
* [ ] Try to pull in any minor bug fixes
* [ ] Rename the repo (maybe TypeScript-lib-generator) or merge it into the TypeScript repository

During this time, @sandersn and I will be the primary contacts on this repo.

I figure I should tag @saschanaz @nd-02110114 @MattiasBuelens @YuichiNukiyama @falsandtru @43081j @a-tarasyuk @irrationalRock since you've either got outstanding PRs, contribute a lot, have contributed a decent amount in the past, or just have a general interest in the updates. Sorry for the noise if not 😅

**Comment by falsandtru** [comment]
Can you remove the deprecated APIs? `ElementTagNameMap` is preventing from defining the SVG `a` tag to the `SVGElementTagNameMap`.

**Comment by DanielRosenwasser** [comment]
I don't know if there's a specific issue that exists (that would make it easier to track), but I think we need to outline a `lib.d.ts` deprecation policy for TypeScript releases.

**Comment by falsandtru** [comment]
origin: https://github.com/Microsoft/TypeScript/issues/20134

**Comment by saschanaz** [comment]
>Rename the repo (maybe TypeScript-lib-generator) or merge it into the TypeScript repository

libdts-generator? 😁

**Comment by TimvdLippe** [comment]
Could you provide another update on the status of this repository? Seems like work has completely stopped, or has it moved somewhere else?

**Comment by saschanaz** [comment]
Should I fork this and maintain my own one? 🤔

**Comment by saschanaz** [comment]
@falsandtru, mind opening a new issue for the SVG thing again?

**Comment by falsandtru** [comment]
I opened many times but all of them were closed: https://github.com/Microsoft/TypeScript/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Afalsandtru+ElementTagNameMap

**Comment by saschanaz** [comment]
Hmm, maybe we can go alternative way. I've heard that there are many new type features that help defining complex things, so maybe we now can redefine it:

```
type ElementTagNameMap = HTMLElementTagNameMap & (only fields from SVGElementTagNameMap which are not in HTMLElementTagNameMap)
```

**Comment by saschanaz** [comment]
I think we can mark this as done.

@github-actions close
