### ISSUE TITLE
some document properties become optional

### ISSUE THREAD

**Issue by ghost** [microsoft/TypeScript-DOM-lib-generator#584]
document.head
document.body
document.documentElement
...
now become an optional property, so all ts code written before 3.1 has to be modified.  I've checked the reason and it's due to whatwg defined this(maybe it's defined by w3c before?)
[https://html.spec.whatwg.org/multipage/dom.html#document](https://html.spec.whatwg.org/multipage/dom.html#document)

I think this change may cause much trouble to people who what to use new ts features yet have to write such ugly code everywhere:
```ts
     console.log(document.body!.width);
```

**Comment by saschanaz** [comment]
#560, #565

@github-actions close
