### ISSUE TITLE
Document idlSouces.json in contribution guide

### ISSUE THREAD

**Issue by Brcrwilliams** [microsoft/TypeScript-DOM-lib-generator#629]
While I was working on #628, @saschanaz informed me that `idlSources.json` can be used to scrape WIDL specs from a web page. This should be documented in the readme, including:

1. What `idlSources.json` is
2. How to add entries
3. How to fetch WIDLs (using `npm run fetch`)
4. Explanation of how this creates a .widl file in /inputfiles/idl/ and that it's used as an input file
5. What specs should be added using this method vs `addedTypes.json`

**Comment by saschanaz** [comment]
idlSources.json is removed in #1034

@github-actions close
