### ISSUE TITLE
TextEncoder and TextDecoder missing from Window object

### ISSUE THREAD

**Issue by Mischala** [microsoft/TypeScript-DOM-lib-generator#663]
consider the following:

```Typescript
export const main = () => {
  const encoder1 = new window.TextEncoder();
  const encoder2 = new TextEncoder();

  const decoder1 = new window.TextDecoder();
  const decoder2 = new TextDecoder();
}
```

`new TextDecoder` and `new window.TextDecoder` should both be valid, and in fact are on all browsers tested, except notably, Edge and IE.
But, TextEncoder and TextDecoder are not defined on the Window type.

**Comment by Mischala** [comment]
#664

**Comment by saschanaz** [comment]
@github-actions close
