### ISSUE TITLE
Unable to define a `.js` file as ServiceWorkerGlobalScope

### ISSUE THREAD

**Issue by wilsonpage** [microsoft/TypeScript-DOM-lib-generator#675]
When a `.js` file is a service-worker, there's no way to define its scope/`self`/`this` as `ServiceWorkerGlobalScope`. This means service-worker only global APIs like `self.skipWaiting()` are undefined and fail Typescript's `checkjs` run.

**Minimal test-case**

https://github.com/wilsonpage/vscode-scope-test-case

**Twitter thread w/ @DanielRosenwasser**

https://twitter.com/drosenwasser/status/1113905694028132352

**Comment by saschanaz** [comment]
#1034 added serviceworker lib and is available on TS 4.4

@github-actions close
