### ISSUE TITLE
Build failing with typescript next

### ISSUE THREAD

**Issue by ahardin13** [microsoft/TypeScript-DOM-lib-generator#702]
Builds with `npm run build` and CI are failing.
https://travis-ci.org/microsoft/TSJS-lib-generator/builds/535138688?utm_source=github_status&utm_medium=notification

After changing typescript to 3.4.4 in package.json and doing an `npm i`, `npm run build` succeeds.

**Comment by saschanaz** [comment]
Fixed by https://github.com/microsoft/TSJS-lib-generator/pull/703

**Comment by saschanaz** [comment]
@github-actions close
