### ISSUE TITLE
Use latest IDL

### ISSUE THREAD

**Issue by dontcallmedom** [microsoft/TypeScript-DOM-lib-generator#816]
From what I can see, this project [extracts IDL fragments from W3C TR version](https://github.com/microsoft/TSJS-lib-generator/blob/master/src/idlfetcher.ts) of the W3C specs, when in most cases, the most uptodate view of what the IDL should be reside in editors draft.

In a separate project called [Reffy](https://github.com/tidoust/reffy), we have set up an automated extraction of the [latest IDL fragment across a large number of W3C and WHATWG specs](https://github.com/tidoust/reffy-reports/tree/master/ed/idl). That [automatic extract is already used to feed automatically](https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md) the [Web-Platform-Tests repository of Web-browser test suites](https://github.com/web-platform-tests/wpt).

It may be interesting to take a similar approach here.

**Comment by foolip** [comment]
From https://github.com/microsoft/TSJS-lib-generator#when-should-a-dom-api-be-included-here it sounds like the number of implementations is an important consideration. This unfortunately can't be determined on a per-spec basis as most specs contain some mature parts and some things yet to be implemented.

Perhaps combining IDL with https://github.com/mdn/browser-compat-data would help here.

I also wonder if it would help to have releases of reffy-reports that have certain guarantees, like all of the IDL being possible to parse with a given version of webidl2.js.

**Comment by saschanaz** [comment]
Definitely a good-to-have, but I wonder what made you open this issue. Is this a blocker for anything?
