### ISSUE TITLE
`HTMLFormElement.requestSubmit` is missing/disabled

### ISSUE THREAD

**Issue by SimonSchick** [microsoft/TypeScript-DOM-lib-generator#848]
I am not sure _why_ it's disabled but it is here:
https://github.com/microsoft/TSJS-lib-generator/blob/master/inputfiles/removedTypes.json#L213

`requestSubmit` is arguably well known and implemented by major browsers
https://html.spec.whatwg.org/multipage/forms.html#dom-form-requestsubmit
https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/requestSubmit

If the removal from typings is intentional could you please provide a reason?
As an additional suggestion: Add a property that describes _why_ a typing is being suppressed.

**Comment by saschanaz** [comment]
Fixed via #1034

@github-actions close
