### ISSUE TITLE
Generating for a single WebIDL file

### ISSUE THREAD

**Issue by iBicha** [microsoft/TypeScript-DOM-lib-generator#849]
Is there an obvious way to generate a file for a single widl file?

**Comment by HolgerJeromin** [comment]
Have you read this?
https://github.com/microsoft/TSJS-lib-generator/blob/master/README.md#build-instructions

**Comment by iBicha** [comment]
> Have you read this?
> https://github.com/microsoft/TSJS-lib-generator/blob/master/README.md#build-instructions

Yes. Building will merge everything in `dom.generated.d.ts`, `webworker.generated.d.ts` and `dom.iterable.generated.d.ts`. I'm looking for generating from a single .widl, into its own `.d.ts` file, not merged with every other WebIDL.

**Comment by HolgerJeromin** [comment]
You could adapt the script if you want to do that often. Or make a diff to find the new things.

**Comment by iBicha** [comment]
There was been multiple instance as I see where generating a separate file is beneficial. #826 #211 
This looks like something needed to be built-in, not adapted for edge cases
