### ISSUE TITLE
Rename master branch to main?

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#871]
There recently are efforts to remove potential racist words like master/slave. Since this repository is less popular than the main TypeScript repo and thus safer from breakages, maybe worth to try renaming.

**Comment by orta** [comment]
Seems reasonable to me, I need to test some of the tools (ensuring the migration of PRs I assume is the tricky part) but I'd prefer it

**Comment by saschanaz** [comment]
GitHub allows changing the base branch right through the web, so the specific problem should probably be okay.

**Comment by saschanaz** [comment]
https://github.com/microsoft/windev named it as "default", BTW.

**Comment by saschanaz** [comment]
It has been `main` for some time.

@github-actions close
