### ISSUE TITLE
HTMLMediaElement and HTMLCanvasElement missing captureStream

### ISSUE THREAD

**Issue by rwoll** [microsoft/TypeScript-DOM-lib-generator#882]
Here are the MDN links showing browser support:

* [MDN `HTMLMediaElement.captureStream(…)`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream)
* [MDN `HTMLCanvasElement.captureStream(…)`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream)

However, it is not documented in W3:

* [w3 `HTMLMediaElement`](https://www.w3.org/TR/2011/WD-html5-20110113/video.html#htmlmediaelement)
* [w3 `HTMLCanvasElement`](https://www.w3.org/TR/2011/WD-html5-20110113/the-canvas-element.html#the-canvas-element)

Would it be ok to add it based on the MDN coverage? If so, I'd be interested in opening a PR. Thanks!

**Comment by saschanaz** [comment]
So far the only stable implementation is Chromium one, we need another stable implementation to add it here.

**Comment by rwoll** [comment]
Thanks for the info. I'm following the Firefox issue; when it lands, I'll circle back and open an MR here.
