### ISSUE TITLE
Missing API set: Constructable StyleSheet

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript-DOM-lib-generator#897]
Code:

```ts
document.adoptedStyleSheets
//       ~~~~~~~~~~~~~~~~~~
declare const a: HTMLDivElement
a.attachShadow({ mode: 'open' }).adoptedStyleSheets
//                               ~~~~~~~~~~~~~~~~~~
const style = new CSSStyleSheet()
style.replace()
//    ~~~~~~~
style.replaceSync()
//    ~~~~~~~~~~~
```

Spec: https://wicg.github.io/construct-stylesheets/#constructing-stylesheets
Docs: https://developers.google.com/web/updates/2019/02/constructable-stylesheets
MDN: not yet
Shipped: Chrome

**Comment by saschanaz** [comment]
This is currently Chrome-only API, and TSJS-lib-generator requires multiple implementations to make sure the API is stable enough with consensus among implementors.

**Comment by HolgerJeromin** [comment]
Should be solved with https://github.com/mdn/browser-compat-data/pull/16411 (Firefox 101)

**Comment by mathe42** [comment]
Yes is here: 
https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/main/baselines/dom.generated.d.ts#L4757
@saschanaz / @Jack-Works This issue can be closed
