### ISSUE TITLE
Notable changes for 4.1 

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-DOM-lib-generator#906]
Changes which could affect builds:

- https://github.com/microsoft/TSJS-lib-generator/pull/873 
   Updates the `specs -> .d.ts` for the DOM .d.ts file to take into account more ways to declare something should not exist. Removing some types which aren't declared to be inside the JS runtime anymore.

- https://github.com/microsoft/TSJS-lib-generator/pull/877
  Adds `webworker.iterable.generated.d.ts` (which will need some compiler work to have it show up correctly)

- https://github.com/microsoft/TSJS-lib-generator/pull/879
  Removes `HkdfCtrParams` from the Web Cryptography API which was deprecated in 2016,  replaced with `HkdfParams` which is in the current spec.

- https://github.com/microsoft/TSJS-lib-generator/pull/883
  Switches the global variable `name` from `never` to `void` which means you will get an error if you read it. This was nearly always a mistake, we used to raise if you write to it, now you get it if you write.

**Comment by HolgerJeromin** [comment]
can this issue be closed? :-)
