### ISSUE TITLE
Missing API: ResizeObserver

### ISSUE THREAD

**Issue by wKich** [microsoft/TypeScript-DOM-lib-generator#908]
Spec: https://drafts.csswg.org/resize-observer/#resize-observer-interface
Mdn: https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver

**Comment by MatthiasKunnen** [comment]
Will be fixed by #847.

**Comment by wKich** [comment]
@MatthiasKunnen, thank you 🙏
