### ISSUE TITLE
Use BCD to automatically disable experimental APIs

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#914]
From https://github.com/microsoft/TSJS-lib-generator/issues/816#issuecomment-576559252.

It's burdensome to manually check whether there are stable implementations for every spec update. Fetching data from BCD will help reducing such burden and may also enable autoupdating.

(Assigning this to myself)

**Comment by HolgerJeromin** [comment]
Just a reminder for those with a bad memory (like me): BCD is https://github.com/mdn/browser-compat-data here :)

**Comment by saschanaz** [comment]
#1034
