### ISSUE TITLE
Missing API: Intl.RelativeTimeFormat

### ISSUE THREAD

**Issue by Jack-Works** [microsoft/TypeScript-DOM-lib-generator#917]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat

This API is widely supported in major browsers

**Comment by saschanaz** [comment]
This should be filed in TypeScript main repo, as this repository only covers HTML/DOM ones.

**Comment by Jack-Works** [comment]
It seems like it already in the esnext
