### ISSUE TITLE
Important changes for 4.2

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-DOM-lib-generator#960]
- Deprecations were added to a lot of DOM types in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/884
- The Streams API was updated in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/890 - this removed some  APIs which weren't supported by browsers and updated the name of some types to match the updated specification.
- Localization APIs now have exact types:

```ts
  const dateOptions = {
     weekday: "long",
     year: "numeric",
     month: "long",
     day: "numeric",
   };

   const date = new Date().toLocaleString("en-US", dateOptions);
``` 

would now need to be 

```
   const date = new Date().toLocaleString("en-US", {
     weekday: "long",
     year: "numeric",
     month: "long",
     day: "numeric",
   });
```

Or to use `as const`

**Comment by HolgerJeromin** [comment]
Can/should we update the typing of querySelector, querySelectorAll and closest, too?

Ref https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/885#issuecomment-725926562

**Comment by orta** [comment]
It was, I used this issue to keep track of breaking changes
