### ISSUE TITLE
ParentNode.replaceChildren is excluded, but it's not clear to me why

### ISSUE THREAD

**Issue by MaienM** [microsoft/TypeScript-DOM-lib-generator#985]
It appears that the method `replaceChildren` on the interface `ParentNode` has explicitly been [excluded](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/3143838d35f07996fdb24a26b80e79c1d42de124/inputfiles/removedTypes.json#L33). It's not clear to me why this is; as far as I can tell it's stable and [present in most browsers](https://github.com/mdn/browser-compat-data/blob/49c5367a7c558e59c9e14a3250ba6584786d343e/api/_mixins/ParentNode__Element.json#L409). This change was introduced in a [seemingly unrelated pull-request](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/870), which doesn't provide any hints as to why this was done. Is there a reason for this? Was this an accident?

**Comment by HolgerJeromin** [comment]
cc @saschanaz

**Comment by saschanaz** [comment]
It wasn't widely available back in 2020. We can now remove the exclusion.

**Comment by saschanaz** [comment]
As in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1008#issuecomment-905792234, this is fixed.

@github-actions close

**Comment by saschanaz** [comment]
@github-actions close
