### ISSUE TITLE
Move the build scripts to src/build

### ISSUE THREAD

**Issue by saschanaz** [microsoft/TypeScript-DOM-lib-generator#986]
`src` currently mixes several scripts, where some runs as a npm command and others are just libraries referenced by `build.ts`.

[types-web](https://github.com/saschanaz/types-web/tree/d9d4a146d6f359f8fae49318e9d773762660715a/src) moved those libraries to `src/build/` for tree readability and I'd like to upstream this structure.

**Comment by orta** [comment]
I think this happened
