### ISSUE TITLE
Breaking changes for 4.3

### ISSUE THREAD

**Issue by orta** [microsoft/TypeScript-DOM-lib-generator#991]
For 4.3, we used the Mozilla [browser-compat-data](https://github.com/mdn/browser-compat-data) to remove types and features which are not used _in any browser_. 

We base the `lib.dom.d.ts` on the specifications from W3C and WHATWG. These specifications are like all projects, and have some cruft on them over time.  Now, we check the data powering caniuse.com to see if there are any implementations of a specification before including the types from that spec in the `lib.dom.d.ts`.

This is automated and running across a lot of specifications, so there's a possibility it has some overreach and we're open to bringing some back if we missed a common case. Some of the types removed:  `Account`  (this is now free to use in your own apps 🎉), `AssertionOptions`, `RTCStatsEventInit`, `MSGestureEvent`, `DeviceLightEvent`, `MSPointerEvent`, `ServiceWorkerMessageEvent` and `WebAuthentication`.

**Comment by Stef-Gijsberts** [comment]
*(I'm not sure where to mention this. If there is a better place, please let me
know.)*

I suspect the automation overreached. I think it removed the
`RTCRtpEncodingParameters.maxFramerate`, which is supported in Safari. [I think]
the reason it was removed is that at the time of checking, there was no known
"Supported" status for any browser on [the caniuse page]. But just now, the
status for Safari was set to "Supported".

It might be worth considering to adjust the automation, such that it does not
remove a feature if its status for a major browser is "Unknown".

[I think]: https://github.com/screensy/screensy/issues/12#issuecomment-863039218
[the caniuse page]: https://caniuse.com/mdn-api_rtcrtpencodingparameters_maxframerate

**Comment by orta** [comment]
If we were to re-add, it wouldn't pass our heuristics which is at least two popular browser support it: https://github.com/microsoft/TypeScript-DOM-lib-generator#what-are-the-typescript-teams-heuristics-for-prs-to-the-dom-apis

So I think this was still right

**Comment by nainkunal933** [comment]
I would like to re-raise @Stef-Gijsberts concern regarding `RTCRtpEncodingParameters.maxFramerate` being removed from 4.3. This is a breaking change for us as well. It seems like since this was last visited `maxFramerate`'s support has increased.

@orta is it possible to re-add `maxFramerate` if it passes the heuristics now?

**Comment by x-epoch** [comment]
I also would like to re-raise this issue since all browsers with latest version are support `maxFramerate` now,  and it is real an import interface for webRTC video control.

**Comment by orta** [comment]
If you followed the linked issue, you'd see that we're open to PRs for it, https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1380#issuecomment-1250255126
