### ISSUE TITLE
Navigator.MediaDevices.getDisplayMedia() is not present. 

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [microsoft/TypeScript-DOM-lib-generator#992]
Hello,

I'm not sure how to edit the types (I can't find reference to navigator anywhere), but your output is incorrect. The `navigator.mediaDevices` object should have a `getDisplayMedia(constraints)` method that returns a `Promise<MediaStream`. 

See here: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia

This has been an issue in the main typescript library for some time now: https://github.com/microsoft/TypeScript/issues/33232 . 

It seems like Typescript's files are generated by this library. This should be an easy fix for someone who knows what they're doing. Alternatively, point me to where the navigator.mediaDevices types are defined and I'll do it myself.

**Comment by HolgerJeromin** [comment]
https://github.com/microsoft/TypeScript-DOM-lib-generator#additions
Says:
> We aim for Proposed recommendation, but can accept Candidate recommendation for stable looking proposals.

https://w3c.github.io/mediacapture-main/#dom-mediadevices-getusermedia
This is still a "W3C Editor's Draft".

**Comment by JustAnotherSoftwareDeveloper** [comment]
If that's the case why do you include `navigator.mediaDevices.getUserMedia`? By admission of the document you linked, that's also a draft.

**Comment by HolgerJeromin** [comment]
Sorry, I found the wrong URI (edited).

navigator.mediaDevices.getUserMedia is in
https://www.w3.org/TR/mediacapture-streams/
Is a W3C Candidate Recommendation

**Comment by JustAnotherSoftwareDeveloper** [comment]
Ok thanks

**Comment by SgAkErRu** [comment]
But https://github.com/microsoft/TypeScript-DOM-lib-generator#additions also says:
> A feature needs to be supported by more than two major browser engines to be included here, to make sure there is a good consensus among vendors: Gecko (Firefox), Blink (Chrome/Edge), and WebKit (Safari).

And about W3C Working Draft:

> If it's at Working draft the additions available in all three of Firefox, Safari and Chromium

But according to Mozilla MDN (https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) this feature supported by all of these browsers since end of 2019.

**Comment by kim3er** [comment]
Looks like `getDisplayMedia` is included in the current build of the main branch.

![getdisplaymedia](https://user-images.githubusercontent.com/250666/131870184-f001884d-2a6c-4f7c-8058-b4f1f190d69e.jpeg)

**Comment by saschanaz** [comment]
Yeah, #1034.

@github-actions close
