### ISSUE TITLE
WebIDL parameter Promise type not converted when in a nested type, e.g. ClipboardItemData

### ISSUE THREAD

**Issue by wffurr** [microsoft/TypeScript-DOM-lib-generator#999]
WebIDL has an implicit conversion mechanism for an ECMAScript value `V` into an IDL `Promise<T>` type.  This means that any function defined in WebIDL that accepts a `Promise<T>` implicitly accepts `T|Promise<T>`.

However, the generated TypeScript typings for a WebIDL function that accepts a `Promise<T>` argument only have the type `Promise<T>`, and not the non-`Promise` `T` type.  The generated typings should have `T|Promise<T>`.

e.g. in https://w3c.github.io/clipboard-apis/#clipboard-interface, the `ClipboardItem` constructor takes`ClipboardItemData` as the values in the `items` record.  The generated typings for that type should be `string|Blobl|Promise<string|Blob>` but instead it's just `Promise<string|Blob>`.

See https://github.com/wffurr/TSJS-lib-generator/commit/9c8bc4b3c8003d48304a5fd439b981d221f33a8d for an example.

**Comment by wffurr** [comment]
I see there's some code to handle this already: https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/a75338e1ea8a958bf08a5745141d2ab8f14ba2ca/src/emitter.ts#L749

It works great for the Payment Request API: https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/a75338e1ea8a958bf08a5745141d2ab8f14ba2ca/baselines/dom.generated.d.ts#L11313

But not for ClipboardItemData because it's in the value position of a record type that is itself a parameter to a function.  The recursion in [`paramsToString`](https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/a75338e1ea8a958bf08a5745141d2ab8f14ba2ca/src/emitter.ts#L747) would have to propagate the knowledge that a parameter is being converted and conditionally modify any `Promise` types that are passed *in* to the browser but not ones come back *from* the browser, e.g. return types of callback arguments but not parameter types of callback arguments.

**Comment by saschanaz** [comment]
#1102

@github-actions close
